// Package main — tools/corpora/prose.go declares renderMeasurementProse,
// the pure function that turns BOTH committed JSON documents
// (corpora/observations.json and corpora/selection.json) into the
// human-readable docs/CORPUS-MEASUREMENT.md. It DERIVES every count it
// renders from the observations — never reads a stored supplier field,
// never transcribes a number by hand — so the prose cannot drift from
// the evidence it cites.
package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/seanb4t/codegraph-go/internal/corpora"
	"github.com/seanb4t/codegraph-go/internal/query"
)

// statusNumeric reads status[section] as a map[string]any and coerces
// every value to int64, tolerating the JSON-decoded float64 shape. It is
// a package-local copy of internal/corpora's (unexported) numericSubmap;
// this tool cannot import the unexported helper, so it re-derives it
// here rather than reaching into another package's internals.
func statusNumeric(status map[string]any, section string) map[string]int64 {
	raw, _ := status[section].(map[string]any)
	out := make(map[string]int64, len(raw))
	for k, v := range raw {
		switch n := v.(type) {
		case float64:
			out[k] = int64(n)
		case int:
			out[k] = int64(n)
		case int64:
			out[k] = n
		}
	}
	return out
}

// renderMeasurementProse returns the complete markdown document, reading
// every count from obs and every policy value from sel. When sel is the
// zero value (no selection file exists yet), the document covers
// observations only and states plainly that no selection has been
// recorded rather than failing or fabricating one.
func renderMeasurementProse(obs corpora.Observations, sel corpora.Selection) string {
	var b strings.Builder

	b.WriteString("# Corpus Measurement Report\n\n")
	b.WriteString("<!--\n")
	b.WriteString("THIS FILE IS GENERATED by `task corpora:measure` from:\n")
	b.WriteString("- corpora/observations.json (generated measurements)\n")
	b.WriteString("- corpora/selection.json (curated selection policy)\n")
	b.WriteString("Do NOT hand-edit this file.\n")
	b.WriteString("-->\n\n")

	if sel.ThresholdRationale == "" {
		b.WriteString("**No selection has been recorded yet.** The observations below are informative; the coverage claim and per-kind thresholds will appear once `corpora/selection.json` is authored.\n\n")
	} else {
		b.WriteString(fmt.Sprintf("**Threshold rationale:** %s\n\n", sel.ThresholdRationale))
	}

	// Locked set / selection overview
	writeLockedSet(&b, obs, sel)

	// Per-kind coverage table
	writeCoverageTable(&b, obs, sel)

	// Per-language file-count table
	writeLanguageTable(&b, obs, sel)

	// Full candidate ledger
	writeCandidateLedger(&b, obs, sel, "observations")

	// Rejected candidates
	writeRejectedCandidates(&b, sel)

	return b.String()
}

func writeLockedSet(b *strings.Builder, obs corpora.Observations, sel corpora.Selection) {
	b.WriteString("## Locked Set\n\n")
	if sel.ThresholdRationale == "" {
		n := len(obs.Observations)
		if n == 0 {
			fmt.Fprint(b, "(no measured entries)")
		} else {
			keys := sortedObsKeys(obs)
			for _, k := range keys {
				o := obs.Observations[k]
				fmt.Fprintf(b, "- %s (%s, %d tracked files)\n", o.Repo, o.License, o.TrackedFiles)
			}
		}
	} else {
		for _, id := range sel.LockedSet {
			o, ok := obs.Observations[id]
			if ok {
				fmt.Fprintf(b, "- %s (%s, %d tracked files)\n", o.Repo, o.License, o.TrackedFiles)
			} else {
				fmt.Fprintf(b, "- %s (no observation — missing from measurements)\n", id)
			}
		}
		if len(sel.LockedSet) == 0 {
			fmt.Fprint(b, "(empty)")
		}
	}
	b.WriteString("\n")
}

func writeCoverageTable(b *strings.Builder, obs corpora.Observations, sel corpora.Selection) {
	b.WriteString("## Per-Kind Coverage\n\n")
	b.WriteString("| Kind | Threshold | Supplying Repository | Measured Count |\n")
	b.WriteString("|------|-----------|---------------------|---------------|\n")

	// Determine which observations are locked
	lockedMap := make(map[string]bool)
	for _, id := range sel.LockedSet {
		lockedMap[id] = true
	}

	// When no selection exists, use all observations as the locked set
	if sel.ThresholdRationale == "" {
		for k := range obs.Observations {
			lockedMap[k] = true
		}
	}

	kindNames := make([]string, 0, len(query.RankEdges))
	for k := range query.RankEdges {
		kindNames = append(kindNames, k)
	}
	sort.Strings(kindNames)

	for _, kind := range kindNames {
		var threshold int64
		var thresholdRace string
		if sel.ThresholdRationale != "" {
			threshold = sel.MinEdgesPerKind[kind]
			thresholdRace = fmt.Sprintf("%d", threshold)
		} else {
			thresholdRace = "(not set)"
		}

		// Derive the supplier: the locked observation with the highest count
		var supplier string
		var maxCount int64
		for id := range lockedMap {
			o, ok := obs.Observations[id]
			if !ok {
				continue
			}
			if c := o.EdgeCount(kind); c > maxCount {
				maxCount = c
				supplier = o.Repo
			}
		}

		if maxCount > 0 || supplier != "" {
			fmt.Fprintf(b, "| %s | %s | %s | %d |\n", kind, thresholdRace, supplier, maxCount)
		} else {
			fmt.Fprintf(b, "| %s | %s | (none) | 0 |\n", kind, thresholdRace)
		}
	}

	// Synthetic kinds
	for _, k := range sel.SyntheticKinds {
		b.WriteString(fmt.Sprintf("| %s | %d | SYNTHETIC — declared by curation, not measured from a third-party repository (D-16) | — |\n", k, sel.MinEdgesPerKind[k]))
	}
	b.WriteString("\n")
}

func writeLanguageTable(b *strings.Builder, obs corpora.Observations, sel corpora.Selection) {
	b.WriteString("## Per-Language File Counts\n\n")
	b.WriteString("| Language | Total Files | Supplying Repositories |\n")
	b.WriteString("|----------|-------------|----------------------|\n")

	lockedMap := make(map[string]bool)
	for _, id := range sel.LockedSet {
		lockedMap[id] = true
	}
	if sel.ThresholdRationale == "" {
		for k := range obs.Observations {
			lockedMap[k] = true
		}
	}

	for _, group := range corpora.PriorityLanguages {
		var total int64
		var repos []string
		for id := range lockedMap {
			o, ok := obs.Observations[id]
			if !ok {
				continue
			}
			cnt := o.LanguageFileCount(group)
			if cnt > 0 {
				total += cnt
				repos = append(repos, o.Repo)
			}
		}
		sort.Strings(repos)
		bar := "PASS"
		if total == 0 {
			bar = "FAIL"
		}
		repoStr := strings.Join(repos, ", ")
		if repoStr == "" {
			repoStr = "(none)"
		}
		fmt.Fprintf(b, "| %s | %d (%s) | %s |\n", group.Name, total, bar, repoStr)
	}
	b.WriteString("\n")
}

func writeCandidateLedger(b *strings.Builder, obs corpora.Observations, sel corpora.Selection, label string) {
	// label parameter is unused; kept for interface stability
	b.WriteString("## All Measured Candidates\n\n")
	keys := sortedObsKeys(obs)
	for _, k := range keys {
		o := obs.Observations[k]
		b.WriteString(fmt.Sprintf("### %s (%s)\n\n", o.Repo, o.SHA[:8]))
		b.WriteString(fmt.Sprintf("- **License:** %s\n", o.License))
		b.WriteString(fmt.Sprintf("- **Tracked files:** %d\n", o.TrackedFiles))
		ek := statusNumeric(o.Status, "edgesByKind")
		if len(ek) > 0 {
			b.WriteString("- **Edges by kind:**\n")
			kindNames := make([]string, 0, len(ek))
			for kk := range ek {
				kindNames = append(kindNames, kk)
			}
			sort.Strings(kindNames)
			for _, kk := range kindNames {
				fmt.Fprintf(b, "  - %s: %d\n", kk, ek[kk])
			}
		}
		fl := statusNumeric(o.Status, "filesByLanguage")
		if len(fl) > 0 {
			b.WriteString("- **Files by language:**\n")
			langNames := make([]string, 0, len(fl))
			for ll := range fl {
				langNames = append(langNames, ll)
			}
			sort.Strings(langNames)
			for _, ll := range langNames {
				fmt.Fprintf(b, "  - %s: %d\n", ll, fl[ll])
			}
		}
	}
	if len(obs.Observations) == 0 {
		fmt.Fprint(b, "(no measured candidates)")
	}
	b.WriteString("\n")
}

func writeRejectedCandidates(b *strings.Builder, sel corpora.Selection) {
	if len(sel.Rejected) == 0 {
		return
	}
	b.WriteString("## Rejected Candidates\n\n")
	for _, r := range sel.Rejected {
		fmt.Fprintf(b, "- **%s:** %s\n", r.Repo, r.Reason)
	}
	b.WriteString("\n")
}

func sortedObsKeys(obs corpora.Observations) []string {
	keys := make([]string, 0, len(obs.Observations))
	for k := range obs.Observations {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}