// Package codegraph.ui.v1 defines codegraph ui's wire protocol: a Connect
// RPC service over the repository's own read-only internal/query.Engine
// (RPC-01, RPC-02). This is a SECOND proto surface, independent of
// internal/schema/graph.proto's on-disk graph-store record format — this
// package never appears on disk, only on the loopback wire.
//
// Additive-only discipline (D-02a, inherited from internal/schema):
// within this package, a field number is never renumbered and never
// reused. When a field is retired, its number is added to a `reserved`
// clause instead of being deleted or repurposed.
//
// Deliberate omission — Query vs Search (plan 01-08): internal/query.Engine
// exposes both Query (full node records for an exact name/kind match) and
// Search (the lightweight Location-only projection of the same match).
// Only Search is exposed here. Query's fuller shape — calls, called-by, and
// the multi-definition candidate set — is strictly subsumed by plan
// 01-09's GetNodeDetail rpc, which covers node lookup; Search covers
// discovery. Exposing both Query and Search on the wire would give the UI
// two overlapping name-lookup rpcs with different result shapes and no
// rule about which to reach for. This service's contract is "every read
// the UI needs", not "every exported method on Engine" — this is that
// contract applied, not an oversight.
//
// Plan 01-10's attachment (RPC-05, D-11/D-12/D-13): a `SourceBlob`-typed
// source field on three messages plan 01-09 declared, at each message's
// next free field number as of the end of 01-09 — exactly the numbers
// 01-09 recorded here as intent, spent now:
//   - GetNodeDetailResponse: source = 9
//   - NodeDefinition: source = 5
//   - ExploreGroup: source = 4
// Plan 01-09's Task 3 known-number fixture (internal/uiserver/readonly_test.go)
// pinned every number allocated through 01-09; this plan EXTENDS that
// fixture with these three plus SourceBlob's own six, and every entry
// 01-09 wrote still holds afterward.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: internal/uiproto/uiv1/ui.proto

package uiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	uiv1 "github.com/seanb4t/codegraph-go/internal/uiproto/uiv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UIServiceName is the fully-qualified name of the UIService service.
	UIServiceName = "codegraph.ui.v1.UIService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UIServiceGetStatusProcedure is the fully-qualified name of the UIService's GetStatus RPC.
	UIServiceGetStatusProcedure = "/codegraph.ui.v1.UIService/GetStatus"
	// UIServiceSearchProcedure is the fully-qualified name of the UIService's Search RPC.
	UIServiceSearchProcedure = "/codegraph.ui.v1.UIService/Search"
	// UIServiceFilesProcedure is the fully-qualified name of the UIService's Files RPC.
	UIServiceFilesProcedure = "/codegraph.ui.v1.UIService/Files"
	// UIServiceCallersProcedure is the fully-qualified name of the UIService's Callers RPC.
	UIServiceCallersProcedure = "/codegraph.ui.v1.UIService/Callers"
	// UIServiceCalleesProcedure is the fully-qualified name of the UIService's Callees RPC.
	UIServiceCalleesProcedure = "/codegraph.ui.v1.UIService/Callees"
	// UIServiceImpactProcedure is the fully-qualified name of the UIService's Impact RPC.
	UIServiceImpactProcedure = "/codegraph.ui.v1.UIService/Impact"
	// UIServiceAffectedProcedure is the fully-qualified name of the UIService's Affected RPC.
	UIServiceAffectedProcedure = "/codegraph.ui.v1.UIService/Affected"
	// UIServiceGetNodeDetailProcedure is the fully-qualified name of the UIService's GetNodeDetail RPC.
	UIServiceGetNodeDetailProcedure = "/codegraph.ui.v1.UIService/GetNodeDetail"
	// UIServiceExploreProcedure is the fully-qualified name of the UIService's Explore RPC.
	UIServiceExploreProcedure = "/codegraph.ui.v1.UIService/Explore"
	// UIServiceGetPermalinkProcedure is the fully-qualified name of the UIService's GetPermalink RPC.
	UIServiceGetPermalinkProcedure = "/codegraph.ui.v1.UIService/GetPermalink"
	// UIServiceGetHealthProcedure is the fully-qualified name of the UIService's GetHealth RPC.
	UIServiceGetHealthProcedure = "/codegraph.ui.v1.UIService/GetHealth"
	// UIServiceFileGraphProcedure is the fully-qualified name of the UIService's FileGraph RPC.
	UIServiceFileGraphProcedure = "/codegraph.ui.v1.UIService/FileGraph"
	// UIServiceFileSymbolsProcedure is the fully-qualified name of the UIService's FileSymbols RPC.
	UIServiceFileSymbolsProcedure = "/codegraph.ui.v1.UIService/FileSymbols"
	// UIServiceWatchGraphProcedure is the fully-qualified name of the UIService's WatchGraph RPC.
	UIServiceWatchGraphProcedure = "/codegraph.ui.v1.UIService/WatchGraph"
)

// UIServiceClient is a client for the codegraph.ui.v1.UIService service.
type UIServiceClient interface {
	GetStatus(context.Context, *connect.Request[uiv1.GetStatusRequest]) (*connect.Response[uiv1.GetStatusResponse], error)
	Search(context.Context, *connect.Request[uiv1.SearchRequest]) (*connect.Response[uiv1.SearchResponse], error)
	Files(context.Context, *connect.Request[uiv1.FilesRequest]) (*connect.Response[uiv1.FilesResponse], error)
	Callers(context.Context, *connect.Request[uiv1.CallersRequest]) (*connect.Response[uiv1.CallersResponse], error)
	Callees(context.Context, *connect.Request[uiv1.CalleesRequest]) (*connect.Response[uiv1.CalleesResponse], error)
	Impact(context.Context, *connect.Request[uiv1.ImpactRequest]) (*connect.Response[uiv1.ImpactResponse], error)
	Affected(context.Context, *connect.Request[uiv1.AffectedRequest]) (*connect.Response[uiv1.AffectedResponse], error)
	GetNodeDetail(context.Context, *connect.Request[uiv1.GetNodeDetailRequest]) (*connect.Response[uiv1.GetNodeDetailResponse], error)
	Explore(context.Context, *connect.Request[uiv1.ExploreRequest]) (*connect.Response[uiv1.ExploreResponse], error)
	// GetPermalink is plan 03-05's tenth rpc (D-06): it turns a repo-relative
	// path and an optional line/end_line anchor into a GitHub blob URL
	// pinned to the commit the index was built at. Read-only: it performs
	// no network operation and mutates nothing (SRV-03). Its path argument
	// is confined by the SAME gate GetNodeDetailRequest.file uses
	// ((*query.Engine).ValidateRepoRelativePath, SRV-05) — no second
	// confinement implementation.
	GetPermalink(context.Context, *connect.Request[uiv1.GetPermalinkRequest]) (*connect.Response[uiv1.GetPermalinkResponse], error)
	// GetHealth is plan 04-03's eleventh rpc (D-01): it projects
	// internal/query.StatusResult's richer per-language file counts,
	// per-kind node/edge counts, pending-change tallies, index-health
	// block and worktree-mismatch detection onto the wire. It exists
	// SEPARATELY from GetStatus, deliberately: GetStatus is fetched on
	// every navigation by the client's status gate (Phase 3's
	// createStatusGate) and must stay cheap, so none of this richer data
	// is added to GetStatusResponse (D-01). Confining
	// gitmeta.DetectIndexMismatch's up-to-four git subprocess cost to this
	// rpc's response shape, rather than GetStatusResponse, is D-02. Read-
	// only and additive per D-02a — it performs no network operation and
	// mutates nothing (SRV-03).
	GetHealth(context.Context, *connect.Request[uiv1.GetHealthRequest]) (*connect.Response[uiv1.GetHealthResponse], error)
	// FileGraph is plan 05-02's twelfth rpc (ENG-03/GRF-02/GRF-04): it
	// projects internal/query.Engine.FileGraph()'s file-granularity
	// dependency rollup onto the wire for the /graph view — every file
	// node, every aggregated source-file-to-target-file edge with its
	// sparse per-kind counts, the three exclusion counters that keep
	// D-03's and D-08's omissions visible rather than silent, and the
	// total cycle count. The rollup is computed FRESH per call from the
	// existing edges (D-05/D-09) — no precomputed projection, no new
	// record kind, no re-indexing. Cycle membership is computed
	// SERVER-SIDE (D-06), so the answer is independent of whichever
	// renderer GRF-01 selects — this is what protects GRF-05's swappable
	// seam. Read-only and additive per D-02a — it performs no network
	// operation and mutates nothing (SRV-03).
	FileGraph(context.Context, *connect.Request[uiv1.FileGraphRequest]) (*connect.Response[uiv1.FileGraphResponse], error)
	// FileSymbols is plan 05-06's thirteenth rpc (GRF-03): it projects
	// internal/query.Engine.FileSymbols's per-file symbol enumeration onto
	// the wire — ordered, capped and counted. It exists SEPARATELY from
	// GetNodeDetail, deliberately: GetNodeDetail's file mode is fetched on
	// every Browse file navigation and carries a path and a source blob
	// only (internal/query.FileDetail has exactly two fields) — it does
	// not enumerate symbols, and hanging a symbol list off it would make
	// every navigation pay for data that view does not render. path is
	// confined by the SAME gate GetNodeDetailRequest.file and
	// GetPermalinkRequest.path use ((*query.Engine).ValidateRepoRelativePath,
	// SRV-05) — no second confinement implementation. Read-only and
	// additive per D-02a — it performs no network operation and mutates
	// nothing (SRV-03).
	FileSymbols(context.Context, *connect.Request[uiv1.FileSymbolsRequest]) (*connect.Response[uiv1.FileSymbolsResponse], error)
	// WatchGraph is this service's fourteenth rpc (RPC-04): the service's
	// FIRST streaming method. It is a server-streaming rpc that pushes one
	// WatchGraphEvent every time the store's authoritative change signal
	// — Meta.last_sync_unix_ms — actually changes, so a client learns of a
	// re-index without polling. It is read-only by construction: it
	// accepts only a resume cursor and mutates nothing, performs no
	// network operation, and is proven so by this package's two existing
	// read-only guards (set-equality against wantUIServiceMethods and the
	// mutating-verb substring check), both re-extended to cover it. Its
	// name was chosen and verified CLEAN against the live mutatingVerbs
	// fixture before being written here — WatchIndex, IndexEvents,
	// StreamIndex and LiveUpdates were all rejected by that same fixture.
	WatchGraph(context.Context, *connect.Request[uiv1.WatchGraphRequest]) (*connect.ServerStreamForClient[uiv1.WatchGraphEvent], error)
}

// NewUIServiceClient constructs a client for the codegraph.ui.v1.UIService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUIServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UIServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	uIServiceMethods := uiv1.File_internal_uiproto_uiv1_ui_proto.Services().ByName("UIService").Methods()
	return &uIServiceClient{
		getStatus: connect.NewClient[uiv1.GetStatusRequest, uiv1.GetStatusResponse](
			httpClient,
			baseURL+UIServiceGetStatusProcedure,
			connect.WithSchema(uIServiceMethods.ByName("GetStatus")),
			connect.WithClientOptions(opts...),
		),
		search: connect.NewClient[uiv1.SearchRequest, uiv1.SearchResponse](
			httpClient,
			baseURL+UIServiceSearchProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Search")),
			connect.WithClientOptions(opts...),
		),
		files: connect.NewClient[uiv1.FilesRequest, uiv1.FilesResponse](
			httpClient,
			baseURL+UIServiceFilesProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Files")),
			connect.WithClientOptions(opts...),
		),
		callers: connect.NewClient[uiv1.CallersRequest, uiv1.CallersResponse](
			httpClient,
			baseURL+UIServiceCallersProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Callers")),
			connect.WithClientOptions(opts...),
		),
		callees: connect.NewClient[uiv1.CalleesRequest, uiv1.CalleesResponse](
			httpClient,
			baseURL+UIServiceCalleesProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Callees")),
			connect.WithClientOptions(opts...),
		),
		impact: connect.NewClient[uiv1.ImpactRequest, uiv1.ImpactResponse](
			httpClient,
			baseURL+UIServiceImpactProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Impact")),
			connect.WithClientOptions(opts...),
		),
		affected: connect.NewClient[uiv1.AffectedRequest, uiv1.AffectedResponse](
			httpClient,
			baseURL+UIServiceAffectedProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Affected")),
			connect.WithClientOptions(opts...),
		),
		getNodeDetail: connect.NewClient[uiv1.GetNodeDetailRequest, uiv1.GetNodeDetailResponse](
			httpClient,
			baseURL+UIServiceGetNodeDetailProcedure,
			connect.WithSchema(uIServiceMethods.ByName("GetNodeDetail")),
			connect.WithClientOptions(opts...),
		),
		explore: connect.NewClient[uiv1.ExploreRequest, uiv1.ExploreResponse](
			httpClient,
			baseURL+UIServiceExploreProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Explore")),
			connect.WithClientOptions(opts...),
		),
		getPermalink: connect.NewClient[uiv1.GetPermalinkRequest, uiv1.GetPermalinkResponse](
			httpClient,
			baseURL+UIServiceGetPermalinkProcedure,
			connect.WithSchema(uIServiceMethods.ByName("GetPermalink")),
			connect.WithClientOptions(opts...),
		),
		getHealth: connect.NewClient[uiv1.GetHealthRequest, uiv1.GetHealthResponse](
			httpClient,
			baseURL+UIServiceGetHealthProcedure,
			connect.WithSchema(uIServiceMethods.ByName("GetHealth")),
			connect.WithClientOptions(opts...),
		),
		fileGraph: connect.NewClient[uiv1.FileGraphRequest, uiv1.FileGraphResponse](
			httpClient,
			baseURL+UIServiceFileGraphProcedure,
			connect.WithSchema(uIServiceMethods.ByName("FileGraph")),
			connect.WithClientOptions(opts...),
		),
		fileSymbols: connect.NewClient[uiv1.FileSymbolsRequest, uiv1.FileSymbolsResponse](
			httpClient,
			baseURL+UIServiceFileSymbolsProcedure,
			connect.WithSchema(uIServiceMethods.ByName("FileSymbols")),
			connect.WithClientOptions(opts...),
		),
		watchGraph: connect.NewClient[uiv1.WatchGraphRequest, uiv1.WatchGraphEvent](
			httpClient,
			baseURL+UIServiceWatchGraphProcedure,
			connect.WithSchema(uIServiceMethods.ByName("WatchGraph")),
			connect.WithClientOptions(opts...),
		),
	}
}

// uIServiceClient implements UIServiceClient.
type uIServiceClient struct {
	getStatus     *connect.Client[uiv1.GetStatusRequest, uiv1.GetStatusResponse]
	search        *connect.Client[uiv1.SearchRequest, uiv1.SearchResponse]
	files         *connect.Client[uiv1.FilesRequest, uiv1.FilesResponse]
	callers       *connect.Client[uiv1.CallersRequest, uiv1.CallersResponse]
	callees       *connect.Client[uiv1.CalleesRequest, uiv1.CalleesResponse]
	impact        *connect.Client[uiv1.ImpactRequest, uiv1.ImpactResponse]
	affected      *connect.Client[uiv1.AffectedRequest, uiv1.AffectedResponse]
	getNodeDetail *connect.Client[uiv1.GetNodeDetailRequest, uiv1.GetNodeDetailResponse]
	explore       *connect.Client[uiv1.ExploreRequest, uiv1.ExploreResponse]
	getPermalink  *connect.Client[uiv1.GetPermalinkRequest, uiv1.GetPermalinkResponse]
	getHealth     *connect.Client[uiv1.GetHealthRequest, uiv1.GetHealthResponse]
	fileGraph     *connect.Client[uiv1.FileGraphRequest, uiv1.FileGraphResponse]
	fileSymbols   *connect.Client[uiv1.FileSymbolsRequest, uiv1.FileSymbolsResponse]
	watchGraph    *connect.Client[uiv1.WatchGraphRequest, uiv1.WatchGraphEvent]
}

// GetStatus calls codegraph.ui.v1.UIService.GetStatus.
func (c *uIServiceClient) GetStatus(ctx context.Context, req *connect.Request[uiv1.GetStatusRequest]) (*connect.Response[uiv1.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// Search calls codegraph.ui.v1.UIService.Search.
func (c *uIServiceClient) Search(ctx context.Context, req *connect.Request[uiv1.SearchRequest]) (*connect.Response[uiv1.SearchResponse], error) {
	return c.search.CallUnary(ctx, req)
}

// Files calls codegraph.ui.v1.UIService.Files.
func (c *uIServiceClient) Files(ctx context.Context, req *connect.Request[uiv1.FilesRequest]) (*connect.Response[uiv1.FilesResponse], error) {
	return c.files.CallUnary(ctx, req)
}

// Callers calls codegraph.ui.v1.UIService.Callers.
func (c *uIServiceClient) Callers(ctx context.Context, req *connect.Request[uiv1.CallersRequest]) (*connect.Response[uiv1.CallersResponse], error) {
	return c.callers.CallUnary(ctx, req)
}

// Callees calls codegraph.ui.v1.UIService.Callees.
func (c *uIServiceClient) Callees(ctx context.Context, req *connect.Request[uiv1.CalleesRequest]) (*connect.Response[uiv1.CalleesResponse], error) {
	return c.callees.CallUnary(ctx, req)
}

// Impact calls codegraph.ui.v1.UIService.Impact.
func (c *uIServiceClient) Impact(ctx context.Context, req *connect.Request[uiv1.ImpactRequest]) (*connect.Response[uiv1.ImpactResponse], error) {
	return c.impact.CallUnary(ctx, req)
}

// Affected calls codegraph.ui.v1.UIService.Affected.
func (c *uIServiceClient) Affected(ctx context.Context, req *connect.Request[uiv1.AffectedRequest]) (*connect.Response[uiv1.AffectedResponse], error) {
	return c.affected.CallUnary(ctx, req)
}

// GetNodeDetail calls codegraph.ui.v1.UIService.GetNodeDetail.
func (c *uIServiceClient) GetNodeDetail(ctx context.Context, req *connect.Request[uiv1.GetNodeDetailRequest]) (*connect.Response[uiv1.GetNodeDetailResponse], error) {
	return c.getNodeDetail.CallUnary(ctx, req)
}

// Explore calls codegraph.ui.v1.UIService.Explore.
func (c *uIServiceClient) Explore(ctx context.Context, req *connect.Request[uiv1.ExploreRequest]) (*connect.Response[uiv1.ExploreResponse], error) {
	return c.explore.CallUnary(ctx, req)
}

// GetPermalink calls codegraph.ui.v1.UIService.GetPermalink.
func (c *uIServiceClient) GetPermalink(ctx context.Context, req *connect.Request[uiv1.GetPermalinkRequest]) (*connect.Response[uiv1.GetPermalinkResponse], error) {
	return c.getPermalink.CallUnary(ctx, req)
}

// GetHealth calls codegraph.ui.v1.UIService.GetHealth.
func (c *uIServiceClient) GetHealth(ctx context.Context, req *connect.Request[uiv1.GetHealthRequest]) (*connect.Response[uiv1.GetHealthResponse], error) {
	return c.getHealth.CallUnary(ctx, req)
}

// FileGraph calls codegraph.ui.v1.UIService.FileGraph.
func (c *uIServiceClient) FileGraph(ctx context.Context, req *connect.Request[uiv1.FileGraphRequest]) (*connect.Response[uiv1.FileGraphResponse], error) {
	return c.fileGraph.CallUnary(ctx, req)
}

// FileSymbols calls codegraph.ui.v1.UIService.FileSymbols.
func (c *uIServiceClient) FileSymbols(ctx context.Context, req *connect.Request[uiv1.FileSymbolsRequest]) (*connect.Response[uiv1.FileSymbolsResponse], error) {
	return c.fileSymbols.CallUnary(ctx, req)
}

// WatchGraph calls codegraph.ui.v1.UIService.WatchGraph.
func (c *uIServiceClient) WatchGraph(ctx context.Context, req *connect.Request[uiv1.WatchGraphRequest]) (*connect.ServerStreamForClient[uiv1.WatchGraphEvent], error) {
	return c.watchGraph.CallServerStream(ctx, req)
}

// UIServiceHandler is an implementation of the codegraph.ui.v1.UIService service.
type UIServiceHandler interface {
	GetStatus(context.Context, *connect.Request[uiv1.GetStatusRequest]) (*connect.Response[uiv1.GetStatusResponse], error)
	Search(context.Context, *connect.Request[uiv1.SearchRequest]) (*connect.Response[uiv1.SearchResponse], error)
	Files(context.Context, *connect.Request[uiv1.FilesRequest]) (*connect.Response[uiv1.FilesResponse], error)
	Callers(context.Context, *connect.Request[uiv1.CallersRequest]) (*connect.Response[uiv1.CallersResponse], error)
	Callees(context.Context, *connect.Request[uiv1.CalleesRequest]) (*connect.Response[uiv1.CalleesResponse], error)
	Impact(context.Context, *connect.Request[uiv1.ImpactRequest]) (*connect.Response[uiv1.ImpactResponse], error)
	Affected(context.Context, *connect.Request[uiv1.AffectedRequest]) (*connect.Response[uiv1.AffectedResponse], error)
	GetNodeDetail(context.Context, *connect.Request[uiv1.GetNodeDetailRequest]) (*connect.Response[uiv1.GetNodeDetailResponse], error)
	Explore(context.Context, *connect.Request[uiv1.ExploreRequest]) (*connect.Response[uiv1.ExploreResponse], error)
	// GetPermalink is plan 03-05's tenth rpc (D-06): it turns a repo-relative
	// path and an optional line/end_line anchor into a GitHub blob URL
	// pinned to the commit the index was built at. Read-only: it performs
	// no network operation and mutates nothing (SRV-03). Its path argument
	// is confined by the SAME gate GetNodeDetailRequest.file uses
	// ((*query.Engine).ValidateRepoRelativePath, SRV-05) — no second
	// confinement implementation.
	GetPermalink(context.Context, *connect.Request[uiv1.GetPermalinkRequest]) (*connect.Response[uiv1.GetPermalinkResponse], error)
	// GetHealth is plan 04-03's eleventh rpc (D-01): it projects
	// internal/query.StatusResult's richer per-language file counts,
	// per-kind node/edge counts, pending-change tallies, index-health
	// block and worktree-mismatch detection onto the wire. It exists
	// SEPARATELY from GetStatus, deliberately: GetStatus is fetched on
	// every navigation by the client's status gate (Phase 3's
	// createStatusGate) and must stay cheap, so none of this richer data
	// is added to GetStatusResponse (D-01). Confining
	// gitmeta.DetectIndexMismatch's up-to-four git subprocess cost to this
	// rpc's response shape, rather than GetStatusResponse, is D-02. Read-
	// only and additive per D-02a — it performs no network operation and
	// mutates nothing (SRV-03).
	GetHealth(context.Context, *connect.Request[uiv1.GetHealthRequest]) (*connect.Response[uiv1.GetHealthResponse], error)
	// FileGraph is plan 05-02's twelfth rpc (ENG-03/GRF-02/GRF-04): it
	// projects internal/query.Engine.FileGraph()'s file-granularity
	// dependency rollup onto the wire for the /graph view — every file
	// node, every aggregated source-file-to-target-file edge with its
	// sparse per-kind counts, the three exclusion counters that keep
	// D-03's and D-08's omissions visible rather than silent, and the
	// total cycle count. The rollup is computed FRESH per call from the
	// existing edges (D-05/D-09) — no precomputed projection, no new
	// record kind, no re-indexing. Cycle membership is computed
	// SERVER-SIDE (D-06), so the answer is independent of whichever
	// renderer GRF-01 selects — this is what protects GRF-05's swappable
	// seam. Read-only and additive per D-02a — it performs no network
	// operation and mutates nothing (SRV-03).
	FileGraph(context.Context, *connect.Request[uiv1.FileGraphRequest]) (*connect.Response[uiv1.FileGraphResponse], error)
	// FileSymbols is plan 05-06's thirteenth rpc (GRF-03): it projects
	// internal/query.Engine.FileSymbols's per-file symbol enumeration onto
	// the wire — ordered, capped and counted. It exists SEPARATELY from
	// GetNodeDetail, deliberately: GetNodeDetail's file mode is fetched on
	// every Browse file navigation and carries a path and a source blob
	// only (internal/query.FileDetail has exactly two fields) — it does
	// not enumerate symbols, and hanging a symbol list off it would make
	// every navigation pay for data that view does not render. path is
	// confined by the SAME gate GetNodeDetailRequest.file and
	// GetPermalinkRequest.path use ((*query.Engine).ValidateRepoRelativePath,
	// SRV-05) — no second confinement implementation. Read-only and
	// additive per D-02a — it performs no network operation and mutates
	// nothing (SRV-03).
	FileSymbols(context.Context, *connect.Request[uiv1.FileSymbolsRequest]) (*connect.Response[uiv1.FileSymbolsResponse], error)
	// WatchGraph is this service's fourteenth rpc (RPC-04): the service's
	// FIRST streaming method. It is a server-streaming rpc that pushes one
	// WatchGraphEvent every time the store's authoritative change signal
	// — Meta.last_sync_unix_ms — actually changes, so a client learns of a
	// re-index without polling. It is read-only by construction: it
	// accepts only a resume cursor and mutates nothing, performs no
	// network operation, and is proven so by this package's two existing
	// read-only guards (set-equality against wantUIServiceMethods and the
	// mutating-verb substring check), both re-extended to cover it. Its
	// name was chosen and verified CLEAN against the live mutatingVerbs
	// fixture before being written here — WatchIndex, IndexEvents,
	// StreamIndex and LiveUpdates were all rejected by that same fixture.
	WatchGraph(context.Context, *connect.Request[uiv1.WatchGraphRequest], *connect.ServerStream[uiv1.WatchGraphEvent]) error
}

// NewUIServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUIServiceHandler(svc UIServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	uIServiceMethods := uiv1.File_internal_uiproto_uiv1_ui_proto.Services().ByName("UIService").Methods()
	uIServiceGetStatusHandler := connect.NewUnaryHandler(
		UIServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(uIServiceMethods.ByName("GetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceSearchHandler := connect.NewUnaryHandler(
		UIServiceSearchProcedure,
		svc.Search,
		connect.WithSchema(uIServiceMethods.ByName("Search")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceFilesHandler := connect.NewUnaryHandler(
		UIServiceFilesProcedure,
		svc.Files,
		connect.WithSchema(uIServiceMethods.ByName("Files")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceCallersHandler := connect.NewUnaryHandler(
		UIServiceCallersProcedure,
		svc.Callers,
		connect.WithSchema(uIServiceMethods.ByName("Callers")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceCalleesHandler := connect.NewUnaryHandler(
		UIServiceCalleesProcedure,
		svc.Callees,
		connect.WithSchema(uIServiceMethods.ByName("Callees")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceImpactHandler := connect.NewUnaryHandler(
		UIServiceImpactProcedure,
		svc.Impact,
		connect.WithSchema(uIServiceMethods.ByName("Impact")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceAffectedHandler := connect.NewUnaryHandler(
		UIServiceAffectedProcedure,
		svc.Affected,
		connect.WithSchema(uIServiceMethods.ByName("Affected")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceGetNodeDetailHandler := connect.NewUnaryHandler(
		UIServiceGetNodeDetailProcedure,
		svc.GetNodeDetail,
		connect.WithSchema(uIServiceMethods.ByName("GetNodeDetail")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceExploreHandler := connect.NewUnaryHandler(
		UIServiceExploreProcedure,
		svc.Explore,
		connect.WithSchema(uIServiceMethods.ByName("Explore")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceGetPermalinkHandler := connect.NewUnaryHandler(
		UIServiceGetPermalinkProcedure,
		svc.GetPermalink,
		connect.WithSchema(uIServiceMethods.ByName("GetPermalink")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceGetHealthHandler := connect.NewUnaryHandler(
		UIServiceGetHealthProcedure,
		svc.GetHealth,
		connect.WithSchema(uIServiceMethods.ByName("GetHealth")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceFileGraphHandler := connect.NewUnaryHandler(
		UIServiceFileGraphProcedure,
		svc.FileGraph,
		connect.WithSchema(uIServiceMethods.ByName("FileGraph")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceFileSymbolsHandler := connect.NewUnaryHandler(
		UIServiceFileSymbolsProcedure,
		svc.FileSymbols,
		connect.WithSchema(uIServiceMethods.ByName("FileSymbols")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceWatchGraphHandler := connect.NewServerStreamHandler(
		UIServiceWatchGraphProcedure,
		svc.WatchGraph,
		connect.WithSchema(uIServiceMethods.ByName("WatchGraph")),
		connect.WithHandlerOptions(opts...),
	)
	return "/codegraph.ui.v1.UIService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UIServiceGetStatusProcedure:
			uIServiceGetStatusHandler.ServeHTTP(w, r)
		case UIServiceSearchProcedure:
			uIServiceSearchHandler.ServeHTTP(w, r)
		case UIServiceFilesProcedure:
			uIServiceFilesHandler.ServeHTTP(w, r)
		case UIServiceCallersProcedure:
			uIServiceCallersHandler.ServeHTTP(w, r)
		case UIServiceCalleesProcedure:
			uIServiceCalleesHandler.ServeHTTP(w, r)
		case UIServiceImpactProcedure:
			uIServiceImpactHandler.ServeHTTP(w, r)
		case UIServiceAffectedProcedure:
			uIServiceAffectedHandler.ServeHTTP(w, r)
		case UIServiceGetNodeDetailProcedure:
			uIServiceGetNodeDetailHandler.ServeHTTP(w, r)
		case UIServiceExploreProcedure:
			uIServiceExploreHandler.ServeHTTP(w, r)
		case UIServiceGetPermalinkProcedure:
			uIServiceGetPermalinkHandler.ServeHTTP(w, r)
		case UIServiceGetHealthProcedure:
			uIServiceGetHealthHandler.ServeHTTP(w, r)
		case UIServiceFileGraphProcedure:
			uIServiceFileGraphHandler.ServeHTTP(w, r)
		case UIServiceFileSymbolsProcedure:
			uIServiceFileSymbolsHandler.ServeHTTP(w, r)
		case UIServiceWatchGraphProcedure:
			uIServiceWatchGraphHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUIServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUIServiceHandler struct{}

func (UnimplementedUIServiceHandler) GetStatus(context.Context, *connect.Request[uiv1.GetStatusRequest]) (*connect.Response[uiv1.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.GetStatus is not implemented"))
}

func (UnimplementedUIServiceHandler) Search(context.Context, *connect.Request[uiv1.SearchRequest]) (*connect.Response[uiv1.SearchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.Search is not implemented"))
}

func (UnimplementedUIServiceHandler) Files(context.Context, *connect.Request[uiv1.FilesRequest]) (*connect.Response[uiv1.FilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.Files is not implemented"))
}

func (UnimplementedUIServiceHandler) Callers(context.Context, *connect.Request[uiv1.CallersRequest]) (*connect.Response[uiv1.CallersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.Callers is not implemented"))
}

func (UnimplementedUIServiceHandler) Callees(context.Context, *connect.Request[uiv1.CalleesRequest]) (*connect.Response[uiv1.CalleesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.Callees is not implemented"))
}

func (UnimplementedUIServiceHandler) Impact(context.Context, *connect.Request[uiv1.ImpactRequest]) (*connect.Response[uiv1.ImpactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.Impact is not implemented"))
}

func (UnimplementedUIServiceHandler) Affected(context.Context, *connect.Request[uiv1.AffectedRequest]) (*connect.Response[uiv1.AffectedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.Affected is not implemented"))
}

func (UnimplementedUIServiceHandler) GetNodeDetail(context.Context, *connect.Request[uiv1.GetNodeDetailRequest]) (*connect.Response[uiv1.GetNodeDetailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.GetNodeDetail is not implemented"))
}

func (UnimplementedUIServiceHandler) Explore(context.Context, *connect.Request[uiv1.ExploreRequest]) (*connect.Response[uiv1.ExploreResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.Explore is not implemented"))
}

func (UnimplementedUIServiceHandler) GetPermalink(context.Context, *connect.Request[uiv1.GetPermalinkRequest]) (*connect.Response[uiv1.GetPermalinkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.GetPermalink is not implemented"))
}

func (UnimplementedUIServiceHandler) GetHealth(context.Context, *connect.Request[uiv1.GetHealthRequest]) (*connect.Response[uiv1.GetHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.GetHealth is not implemented"))
}

func (UnimplementedUIServiceHandler) FileGraph(context.Context, *connect.Request[uiv1.FileGraphRequest]) (*connect.Response[uiv1.FileGraphResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.FileGraph is not implemented"))
}

func (UnimplementedUIServiceHandler) FileSymbols(context.Context, *connect.Request[uiv1.FileSymbolsRequest]) (*connect.Response[uiv1.FileSymbolsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.FileSymbols is not implemented"))
}

func (UnimplementedUIServiceHandler) WatchGraph(context.Context, *connect.Request[uiv1.WatchGraphRequest], *connect.ServerStream[uiv1.WatchGraphEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.WatchGraph is not implemented"))
}
