// Package codegraph.ui.v1 defines codegraph ui's wire protocol: a Connect
// RPC service over the repository's own read-only internal/query.Engine
// (RPC-01, RPC-02). This is a SECOND proto surface, independent of
// internal/schema/graph.proto's on-disk graph-store record format — this
// package never appears on disk, only on the loopback wire.
//
// Additive-only discipline (D-02a, inherited from internal/schema):
// within this package, a field number is never renumbered and never
// reused. When a field is retired, its number is added to a `reserved`
// clause instead of being deleted or repurposed.
//
// Deliberate omission — Query vs Search (plan 01-08): internal/query.Engine
// exposes both Query (full node records for an exact name/kind match) and
// Search (the lightweight Location-only projection of the same match).
// Only Search is exposed here. Query's fuller shape — calls, called-by, and
// the multi-definition candidate set — is strictly subsumed by plan
// 01-09's GetNodeDetail rpc, which covers node lookup; Search covers
// discovery. Exposing both Query and Search on the wire would give the UI
// two overlapping name-lookup rpcs with different result shapes and no
// rule about which to reach for. This service's contract is "every read
// the UI needs", not "every exported method on Engine" — this is that
// contract applied, not an oversight.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: internal/uiproto/uiv1/ui.proto

package uiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	uiv1 "github.com/seanb4t/codegraph-go/internal/uiproto/uiv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UIServiceName is the fully-qualified name of the UIService service.
	UIServiceName = "codegraph.ui.v1.UIService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UIServiceGetStatusProcedure is the fully-qualified name of the UIService's GetStatus RPC.
	UIServiceGetStatusProcedure = "/codegraph.ui.v1.UIService/GetStatus"
	// UIServiceSearchProcedure is the fully-qualified name of the UIService's Search RPC.
	UIServiceSearchProcedure = "/codegraph.ui.v1.UIService/Search"
	// UIServiceFilesProcedure is the fully-qualified name of the UIService's Files RPC.
	UIServiceFilesProcedure = "/codegraph.ui.v1.UIService/Files"
	// UIServiceCallersProcedure is the fully-qualified name of the UIService's Callers RPC.
	UIServiceCallersProcedure = "/codegraph.ui.v1.UIService/Callers"
	// UIServiceCalleesProcedure is the fully-qualified name of the UIService's Callees RPC.
	UIServiceCalleesProcedure = "/codegraph.ui.v1.UIService/Callees"
	// UIServiceImpactProcedure is the fully-qualified name of the UIService's Impact RPC.
	UIServiceImpactProcedure = "/codegraph.ui.v1.UIService/Impact"
	// UIServiceAffectedProcedure is the fully-qualified name of the UIService's Affected RPC.
	UIServiceAffectedProcedure = "/codegraph.ui.v1.UIService/Affected"
)

// UIServiceClient is a client for the codegraph.ui.v1.UIService service.
type UIServiceClient interface {
	GetStatus(context.Context, *connect.Request[uiv1.GetStatusRequest]) (*connect.Response[uiv1.GetStatusResponse], error)
	Search(context.Context, *connect.Request[uiv1.SearchRequest]) (*connect.Response[uiv1.SearchResponse], error)
	Files(context.Context, *connect.Request[uiv1.FilesRequest]) (*connect.Response[uiv1.FilesResponse], error)
	Callers(context.Context, *connect.Request[uiv1.CallersRequest]) (*connect.Response[uiv1.CallersResponse], error)
	Callees(context.Context, *connect.Request[uiv1.CalleesRequest]) (*connect.Response[uiv1.CalleesResponse], error)
	Impact(context.Context, *connect.Request[uiv1.ImpactRequest]) (*connect.Response[uiv1.ImpactResponse], error)
	Affected(context.Context, *connect.Request[uiv1.AffectedRequest]) (*connect.Response[uiv1.AffectedResponse], error)
}

// NewUIServiceClient constructs a client for the codegraph.ui.v1.UIService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUIServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UIServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	uIServiceMethods := uiv1.File_internal_uiproto_uiv1_ui_proto.Services().ByName("UIService").Methods()
	return &uIServiceClient{
		getStatus: connect.NewClient[uiv1.GetStatusRequest, uiv1.GetStatusResponse](
			httpClient,
			baseURL+UIServiceGetStatusProcedure,
			connect.WithSchema(uIServiceMethods.ByName("GetStatus")),
			connect.WithClientOptions(opts...),
		),
		search: connect.NewClient[uiv1.SearchRequest, uiv1.SearchResponse](
			httpClient,
			baseURL+UIServiceSearchProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Search")),
			connect.WithClientOptions(opts...),
		),
		files: connect.NewClient[uiv1.FilesRequest, uiv1.FilesResponse](
			httpClient,
			baseURL+UIServiceFilesProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Files")),
			connect.WithClientOptions(opts...),
		),
		callers: connect.NewClient[uiv1.CallersRequest, uiv1.CallersResponse](
			httpClient,
			baseURL+UIServiceCallersProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Callers")),
			connect.WithClientOptions(opts...),
		),
		callees: connect.NewClient[uiv1.CalleesRequest, uiv1.CalleesResponse](
			httpClient,
			baseURL+UIServiceCalleesProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Callees")),
			connect.WithClientOptions(opts...),
		),
		impact: connect.NewClient[uiv1.ImpactRequest, uiv1.ImpactResponse](
			httpClient,
			baseURL+UIServiceImpactProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Impact")),
			connect.WithClientOptions(opts...),
		),
		affected: connect.NewClient[uiv1.AffectedRequest, uiv1.AffectedResponse](
			httpClient,
			baseURL+UIServiceAffectedProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Affected")),
			connect.WithClientOptions(opts...),
		),
	}
}

// uIServiceClient implements UIServiceClient.
type uIServiceClient struct {
	getStatus *connect.Client[uiv1.GetStatusRequest, uiv1.GetStatusResponse]
	search    *connect.Client[uiv1.SearchRequest, uiv1.SearchResponse]
	files     *connect.Client[uiv1.FilesRequest, uiv1.FilesResponse]
	callers   *connect.Client[uiv1.CallersRequest, uiv1.CallersResponse]
	callees   *connect.Client[uiv1.CalleesRequest, uiv1.CalleesResponse]
	impact    *connect.Client[uiv1.ImpactRequest, uiv1.ImpactResponse]
	affected  *connect.Client[uiv1.AffectedRequest, uiv1.AffectedResponse]
}

// GetStatus calls codegraph.ui.v1.UIService.GetStatus.
func (c *uIServiceClient) GetStatus(ctx context.Context, req *connect.Request[uiv1.GetStatusRequest]) (*connect.Response[uiv1.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// Search calls codegraph.ui.v1.UIService.Search.
func (c *uIServiceClient) Search(ctx context.Context, req *connect.Request[uiv1.SearchRequest]) (*connect.Response[uiv1.SearchResponse], error) {
	return c.search.CallUnary(ctx, req)
}

// Files calls codegraph.ui.v1.UIService.Files.
func (c *uIServiceClient) Files(ctx context.Context, req *connect.Request[uiv1.FilesRequest]) (*connect.Response[uiv1.FilesResponse], error) {
	return c.files.CallUnary(ctx, req)
}

// Callers calls codegraph.ui.v1.UIService.Callers.
func (c *uIServiceClient) Callers(ctx context.Context, req *connect.Request[uiv1.CallersRequest]) (*connect.Response[uiv1.CallersResponse], error) {
	return c.callers.CallUnary(ctx, req)
}

// Callees calls codegraph.ui.v1.UIService.Callees.
func (c *uIServiceClient) Callees(ctx context.Context, req *connect.Request[uiv1.CalleesRequest]) (*connect.Response[uiv1.CalleesResponse], error) {
	return c.callees.CallUnary(ctx, req)
}

// Impact calls codegraph.ui.v1.UIService.Impact.
func (c *uIServiceClient) Impact(ctx context.Context, req *connect.Request[uiv1.ImpactRequest]) (*connect.Response[uiv1.ImpactResponse], error) {
	return c.impact.CallUnary(ctx, req)
}

// Affected calls codegraph.ui.v1.UIService.Affected.
func (c *uIServiceClient) Affected(ctx context.Context, req *connect.Request[uiv1.AffectedRequest]) (*connect.Response[uiv1.AffectedResponse], error) {
	return c.affected.CallUnary(ctx, req)
}

// UIServiceHandler is an implementation of the codegraph.ui.v1.UIService service.
type UIServiceHandler interface {
	GetStatus(context.Context, *connect.Request[uiv1.GetStatusRequest]) (*connect.Response[uiv1.GetStatusResponse], error)
	Search(context.Context, *connect.Request[uiv1.SearchRequest]) (*connect.Response[uiv1.SearchResponse], error)
	Files(context.Context, *connect.Request[uiv1.FilesRequest]) (*connect.Response[uiv1.FilesResponse], error)
	Callers(context.Context, *connect.Request[uiv1.CallersRequest]) (*connect.Response[uiv1.CallersResponse], error)
	Callees(context.Context, *connect.Request[uiv1.CalleesRequest]) (*connect.Response[uiv1.CalleesResponse], error)
	Impact(context.Context, *connect.Request[uiv1.ImpactRequest]) (*connect.Response[uiv1.ImpactResponse], error)
	Affected(context.Context, *connect.Request[uiv1.AffectedRequest]) (*connect.Response[uiv1.AffectedResponse], error)
}

// NewUIServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUIServiceHandler(svc UIServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	uIServiceMethods := uiv1.File_internal_uiproto_uiv1_ui_proto.Services().ByName("UIService").Methods()
	uIServiceGetStatusHandler := connect.NewUnaryHandler(
		UIServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(uIServiceMethods.ByName("GetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceSearchHandler := connect.NewUnaryHandler(
		UIServiceSearchProcedure,
		svc.Search,
		connect.WithSchema(uIServiceMethods.ByName("Search")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceFilesHandler := connect.NewUnaryHandler(
		UIServiceFilesProcedure,
		svc.Files,
		connect.WithSchema(uIServiceMethods.ByName("Files")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceCallersHandler := connect.NewUnaryHandler(
		UIServiceCallersProcedure,
		svc.Callers,
		connect.WithSchema(uIServiceMethods.ByName("Callers")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceCalleesHandler := connect.NewUnaryHandler(
		UIServiceCalleesProcedure,
		svc.Callees,
		connect.WithSchema(uIServiceMethods.ByName("Callees")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceImpactHandler := connect.NewUnaryHandler(
		UIServiceImpactProcedure,
		svc.Impact,
		connect.WithSchema(uIServiceMethods.ByName("Impact")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceAffectedHandler := connect.NewUnaryHandler(
		UIServiceAffectedProcedure,
		svc.Affected,
		connect.WithSchema(uIServiceMethods.ByName("Affected")),
		connect.WithHandlerOptions(opts...),
	)
	return "/codegraph.ui.v1.UIService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UIServiceGetStatusProcedure:
			uIServiceGetStatusHandler.ServeHTTP(w, r)
		case UIServiceSearchProcedure:
			uIServiceSearchHandler.ServeHTTP(w, r)
		case UIServiceFilesProcedure:
			uIServiceFilesHandler.ServeHTTP(w, r)
		case UIServiceCallersProcedure:
			uIServiceCallersHandler.ServeHTTP(w, r)
		case UIServiceCalleesProcedure:
			uIServiceCalleesHandler.ServeHTTP(w, r)
		case UIServiceImpactProcedure:
			uIServiceImpactHandler.ServeHTTP(w, r)
		case UIServiceAffectedProcedure:
			uIServiceAffectedHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUIServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUIServiceHandler struct{}

func (UnimplementedUIServiceHandler) GetStatus(context.Context, *connect.Request[uiv1.GetStatusRequest]) (*connect.Response[uiv1.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.GetStatus is not implemented"))
}

func (UnimplementedUIServiceHandler) Search(context.Context, *connect.Request[uiv1.SearchRequest]) (*connect.Response[uiv1.SearchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.Search is not implemented"))
}

func (UnimplementedUIServiceHandler) Files(context.Context, *connect.Request[uiv1.FilesRequest]) (*connect.Response[uiv1.FilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.Files is not implemented"))
}

func (UnimplementedUIServiceHandler) Callers(context.Context, *connect.Request[uiv1.CallersRequest]) (*connect.Response[uiv1.CallersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.Callers is not implemented"))
}

func (UnimplementedUIServiceHandler) Callees(context.Context, *connect.Request[uiv1.CalleesRequest]) (*connect.Response[uiv1.CalleesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.Callees is not implemented"))
}

func (UnimplementedUIServiceHandler) Impact(context.Context, *connect.Request[uiv1.ImpactRequest]) (*connect.Response[uiv1.ImpactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.Impact is not implemented"))
}

func (UnimplementedUIServiceHandler) Affected(context.Context, *connect.Request[uiv1.AffectedRequest]) (*connect.Response[uiv1.AffectedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codegraph.ui.v1.UIService.Affected is not implemented"))
}
