// Package codegraph.ui.v1 defines codegraph ui's wire protocol: a Connect
// RPC service over the repository's own read-only internal/query.Engine
// (RPC-01, RPC-02). This is a SECOND proto surface, independent of
// internal/schema/graph.proto's on-disk graph-store record format — this
// package never appears on disk, only on the loopback wire.
//
// Additive-only discipline (D-02a, inherited from internal/schema):
// within this package, a field number is never renumbered and never
// reused. When a field is retired, its number is added to a `reserved`
// clause instead of being deleted or repurposed.
//
// Deliberate omission — Query vs Search (plan 01-08): internal/query.Engine
// exposes both Query (full node records for an exact name/kind match) and
// Search (the lightweight Location-only projection of the same match).
// Only Search is exposed here. Query's fuller shape — calls, called-by, and
// the multi-definition candidate set — is strictly subsumed by plan
// 01-09's GetNodeDetail rpc, which covers node lookup; Search covers
// discovery. Exposing both Query and Search on the wire would give the UI
// two overlapping name-lookup rpcs with different result shapes and no
// rule about which to reach for. This service's contract is "every read
// the UI needs", not "every exported method on Engine" — this is that
// contract applied, not an oversight.
//
// Plan 01-10's forthcoming attachment (documentation only, deliberately
// NOT a `reserved` clause — a `reserved` here would forbid the very field
// numbers 01-10 needs to use, and a descriptor carries no comments, so an
// undeclared number cannot be pinned by any guard; see plan 01-09's
// SUMMARY for the full reasoning). Plan 01-10 attaches a `SourceBlob`-
// typed source field to three messages this plan (01-09) declares, at
// each message's next free field number as of the end of 01-09:
//   - GetNodeDetailResponse: next free number 9
//   - NodeDefinition: next free number 5
//   - ExploreGroup: next free number 4
// Plan 01-09's Task 3 known-number fixture pins every number allocated
// through 01-09 over the generated descriptor, so 01-10 may ADD those
// three fields but cannot disturb one already shipped.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/uiproto/uiv1/ui.proto

package uiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeDetailMode discriminates which of GetNodeDetailResponse's three
// shapes is populated, mirroring internal/query.NodeDetailMode's three
// constants exactly (D-02). NODE_DETAIL_MODE_UNSPECIFIED is the required
// proto3 zero value and is never a mode NodeDetail itself produces.
type NodeDetailMode int32

const (
	NodeDetailMode_NODE_DETAIL_MODE_UNSPECIFIED NodeDetailMode = 0
	NodeDetailMode_NODE_DETAIL_MODE_FILE        NodeDetailMode = 1
	NodeDetailMode_NODE_DETAIL_MODE_SINGLE_DEF  NodeDetailMode = 2
	NodeDetailMode_NODE_DETAIL_MODE_MULTI_DEF   NodeDetailMode = 3
)

// Enum value maps for NodeDetailMode.
var (
	NodeDetailMode_name = map[int32]string{
		0: "NODE_DETAIL_MODE_UNSPECIFIED",
		1: "NODE_DETAIL_MODE_FILE",
		2: "NODE_DETAIL_MODE_SINGLE_DEF",
		3: "NODE_DETAIL_MODE_MULTI_DEF",
	}
	NodeDetailMode_value = map[string]int32{
		"NODE_DETAIL_MODE_UNSPECIFIED": 0,
		"NODE_DETAIL_MODE_FILE":        1,
		"NODE_DETAIL_MODE_SINGLE_DEF":  2,
		"NODE_DETAIL_MODE_MULTI_DEF":   3,
	}
)

func (x NodeDetailMode) Enum() *NodeDetailMode {
	p := new(NodeDetailMode)
	*p = x
	return p
}

func (x NodeDetailMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeDetailMode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_uiproto_uiv1_ui_proto_enumTypes[0].Descriptor()
}

func (NodeDetailMode) Type() protoreflect.EnumType {
	return &file_internal_uiproto_uiv1_ui_proto_enumTypes[0]
}

func (x NodeDetailMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeDetailMode.Descriptor instead.
func (NodeDetailMode) EnumDescriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{0}
}

// Node is the shared wire projection of a graph symbol record — the
// fields a UI view actually renders, mirroring internal/schema/graph.proto's
// Node message field-for-field (minus its reserved 50-59 annotation
// range, which has no consumer yet on either surface). Defined once here
// and reused across every response that needs a full node rather than a
// bare Location, so Phases 3-6 never have to reconcile divergent
// per-response node shapes for the same underlying record.
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	QualifiedName string                 `protobuf:"bytes,4,opt,name=qualified_name,json=qualifiedName,proto3" json:"qualified_name,omitempty"`
	FilePath      string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	StartLine     int32                  `protobuf:"varint,7,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine       int32                  `protobuf:"varint,8,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	StartCol      int32                  `protobuf:"varint,9,opt,name=start_col,json=startCol,proto3" json:"start_col,omitempty"`
	EndCol        int32                  `protobuf:"varint,10,opt,name=end_col,json=endCol,proto3" json:"end_col,omitempty"`
	Signature     string                 `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	Docstring     string                 `protobuf:"bytes,12,opt,name=docstring,proto3" json:"docstring,omitempty"`
	Visibility    string                 `protobuf:"bytes,13,opt,name=visibility,proto3" json:"visibility,omitempty"`
	IsExported    bool                   `protobuf:"varint,14,opt,name=is_exported,json=isExported,proto3" json:"is_exported,omitempty"`
	ReturnType    string                 `protobuf:"bytes,15,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetQualifiedName() string {
	if x != nil {
		return x.QualifiedName
	}
	return ""
}

func (x *Node) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Node) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Node) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *Node) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *Node) GetStartCol() int32 {
	if x != nil {
		return x.StartCol
	}
	return 0
}

func (x *Node) GetEndCol() int32 {
	if x != nil {
		return x.EndCol
	}
	return 0
}

func (x *Node) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Node) GetDocstring() string {
	if x != nil {
		return x.Docstring
	}
	return ""
}

func (x *Node) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Node) GetIsExported() bool {
	if x != nil {
		return x.IsExported
	}
	return false
}

func (x *Node) GetReturnType() string {
	if x != nil {
		return x.ReturnType
	}
	return ""
}

// Location is the shared wire projection of internal/query.Location — a
// lightweight name/kind/file/line-only reference, with no source body or
// signature. Every traversal rpc's repeated result (Search, Callers,
// Callees, Impact, Affected) reuses this one message rather than a
// per-rpc variant.
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	StartLine     int32                  `protobuf:"varint,4,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Location) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Location) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

// GetStatusRequest is presently empty of consulted fields — v1's server
// binds exactly one repository at startup (uiserver.Options.RepoPath, an
// unwired field per D-08) and every rpc reports on that repository.
type GetStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path is RESERVED for a future milestone where one server process
	// answers for more than one repository; the v1 handler does not read
	// it — every response reports on the server's own configured
	// RepoPath regardless of this field's value. Declared now, rather
	// than left for a later field-number addition, so the wire shape is
	// stable before any client depends on it.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// GetStatusResponse is the uiv1 projection of internal/query.StatusResult
// (D-06): a bounded subset sufficient for this tracer's health check,
// not the full CLI `status --json` shape. The mapping table lives in
// internal/uiserver/handlers.go's GetStatus doc comment.
type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// initialized mirrors StatusResult.Initialized: true whenever this
	// response was produced from a successfully opened Engine. Absent
	// (zero value: false) has no meaning yet in this plan — SRV-04's
	// degrade path (D-16, a later plan) is the first caller that can
	// legitimately answer with initialized=false from a locked store.
	Initialized bool `protobuf:"varint,1,opt,name=initialized,proto3" json:"initialized,omitempty"`
	// version mirrors StatusResult.Version — the schema version string
	// (fmt.Sprintf("%d", schema.SchemaVersion)), not a codegraph-go
	// release version (D-06, status.go's mapping table).
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// node_count mirrors StatusResult.NodeCount, a live graphstore.Reader
	// scan result. Absent (zero value: 0) means the store reported no
	// nodes, not "unknown" — this plan's GetStatus never returns a
	// zero-valued node_count for any other reason, since a failed Engine
	// open never reaches message construction in this plan.
	NodeCount int64 `protobuf:"varint,3,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	// edge_count mirrors StatusResult.EdgeCount, the same discipline as
	// node_count.
	EdgeCount int64 `protobuf:"varint,4,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	// file_count mirrors StatusResult.FileCount, the same discipline as
	// node_count.
	FileCount int64 `protobuf:"varint,5,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	// stale mirrors StatusResult.Stale (D-04a): true when a sync is
	// pending (the watcher/daemon signal file exists, or the newest
	// on-disk source mtime is newer than the last recorded sync).
	Stale bool `protobuf:"varint,6,opt,name=stale,proto3" json:"stale,omitempty"`
	// commit_sha (ENG-04, D-05/D-06) is the git commit this graph was
	// indexed at, read through (*query.Engine).IndexMeta and
	// schema.IndexedCommitSHA. Empty means the graph predates Meta field 8
	// (a pre-upgrade graph) or the index was built outside a git checkout
	// — both cases are "unknown", never an error, and the client must
	// render "unknown" rather than treating an empty value as a failure.
	//
	// Field numbers 8 and 9 on this message are ALREADY ALLOCATED to plan
	// 01-11's store_exists and indexing_in_progress fields (D-14/D-16's
	// degrade path) and MUST NOT be assigned here or by any other plan — a
	// numbering collision between two plans sharing this phase is exactly
	// what D-02a's additive-only, never-renumbered discipline exists to
	// prevent.
	CommitSha     string `protobuf:"bytes,7,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetNodeCount() int64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *GetStatusResponse) GetEdgeCount() int64 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

func (x *GetStatusResponse) GetFileCount() int64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *GetStatusResponse) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *GetStatusResponse) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

// SearchRequest carries internal/query.Engine.Search's three arguments
// unchanged. limit is passed straight through: validateLimit and MaxLimit
// already bound it server-side for every caller, so this rpc adds no
// second copy of that rule that could drift from the Engine's own.
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{4}
}

func (x *SearchRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *SearchRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SearchResponse carries Search's Location matches, in the same order
// Engine.Search returns them.
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

// FileEntry is the wire projection of internal/query.FileEntry: one
// browsed file's identity plus its stored aggregate symbol/edge counts.
type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	NodeCount     int64                  `protobuf:"varint,3,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	EdgeCount     int64                  `protobuf:"varint,4,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{6}
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *FileEntry) GetNodeCount() int64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *FileEntry) GetEdgeCount() int64 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

// FileTreeNode is the wire projection of internal/query.FileTreeNode —
// one node of the "tree" format's nested directory projection. A
// directory node carries name, is_dir=true, and children, and NO path or
// language; a leaf (file) node carries name, is_dir=false, path and
// language, and NO children. A client that assumes every node carries a
// path will break on the first directory — this asymmetry is the wire
// shape's defining property, not an omission.
type FileTreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Children      []*FileTreeNode        `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTreeNode) Reset() {
	*x = FileTreeNode{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTreeNode) ProtoMessage() {}

func (x *FileTreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTreeNode.ProtoReflect.Descriptor instead.
func (*FileTreeNode) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{7}
}

func (x *FileTreeNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileTreeNode) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileTreeNode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileTreeNode) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *FileTreeNode) GetChildren() []*FileTreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

// FilesRequest carries internal/query.FilesOptions' fields unchanged.
// depth and format are passed straight through: Engine.Files' own
// validateFilesDepth and format rejection already bound them
// server-side for every caller, so this rpc adds no second copy of
// either rule.
type FilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Filter        string                 `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Dir           string                 `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`
	Depth         int32                  `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesRequest) Reset() {
	*x = FilesRequest{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesRequest) ProtoMessage() {}

func (x *FilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesRequest.ProtoReflect.Descriptor instead.
func (*FilesRequest) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{8}
}

func (x *FilesRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *FilesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *FilesRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *FilesRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *FilesRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// FilesResponse is the wire projection of internal/query.FilesResult — a
// UNION, not two independent collections: format selects which ONE of
// files (the "flat" format) or tree (the "tree" format) is populated: a
// "flat" response carries a populated files and an EMPTY tree; a "tree"
// response carries a populated tree and an EMPTY files. A client must
// read format before deciding which field to render, exactly as
// internal/query/files.go's own FilesResult contract already requires
// its CLI/MCP callers to do.
type FilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Files         []*FileEntry           `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Tree          []*FileTreeNode        `protobuf:"bytes,3,rep,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesResponse) Reset() {
	*x = FilesResponse{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesResponse) ProtoMessage() {}

func (x *FilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesResponse.ProtoReflect.Descriptor instead.
func (*FilesResponse) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{9}
}

func (x *FilesResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *FilesResponse) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FilesResponse) GetTree() []*FileTreeNode {
	if x != nil {
		return x.Tree
	}
	return nil
}

// CallersRequest carries internal/query.Engine.Callers' two arguments
// unchanged. limit is passed straight through — validateLimit and
// MaxLimit already bound it server-side for every caller.
type CallersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallersRequest) Reset() {
	*x = CallersRequest{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallersRequest) ProtoMessage() {}

func (x *CallersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallersRequest.ProtoReflect.Descriptor instead.
func (*CallersRequest) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{10}
}

func (x *CallersRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CallersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// CallersResponse mirrors internal/query.CallersResult's shape.
type CallersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Callers       []*Location            `protobuf:"bytes,2,rep,name=callers,proto3" json:"callers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallersResponse) Reset() {
	*x = CallersResponse{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallersResponse) ProtoMessage() {}

func (x *CallersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallersResponse.ProtoReflect.Descriptor instead.
func (*CallersResponse) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{11}
}

func (x *CallersResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CallersResponse) GetCallers() []*Location {
	if x != nil {
		return x.Callers
	}
	return nil
}

// CalleesRequest carries internal/query.Engine.Callees' two arguments
// unchanged, the same discipline as CallersRequest.
type CalleesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalleesRequest) Reset() {
	*x = CalleesRequest{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalleesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalleesRequest) ProtoMessage() {}

func (x *CalleesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalleesRequest.ProtoReflect.Descriptor instead.
func (*CalleesRequest) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{12}
}

func (x *CalleesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CalleesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// CalleesResponse mirrors internal/query.CalleesResult's shape.
type CalleesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Callees       []*Location            `protobuf:"bytes,2,rep,name=callees,proto3" json:"callees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalleesResponse) Reset() {
	*x = CalleesResponse{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalleesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalleesResponse) ProtoMessage() {}

func (x *CalleesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalleesResponse.ProtoReflect.Descriptor instead.
func (*CalleesResponse) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{13}
}

func (x *CalleesResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CalleesResponse) GetCallees() []*Location {
	if x != nil {
		return x.Callees
	}
	return nil
}

// ImpactRequest carries internal/query.Engine.Impact's two arguments
// unchanged. depth is passed straight through — validateDepth and
// clampDepth already bound/clamp it server-side for every caller.
type ImpactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpactRequest) Reset() {
	*x = ImpactRequest{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpactRequest) ProtoMessage() {}

func (x *ImpactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpactRequest.ProtoReflect.Descriptor instead.
func (*ImpactRequest) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{14}
}

func (x *ImpactRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ImpactRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// ImpactResponse mirrors internal/query.ImpactResult's shape. depth is
// the CLAMPED depth Impact actually used (clampDepth's return value,
// echoed back by the Engine itself), not the caller's raw request value.
type ImpactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	NodeCount     int32                  `protobuf:"varint,3,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	EdgeCount     int32                  `protobuf:"varint,4,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	Affected      []*Location            `protobuf:"bytes,5,rep,name=affected,proto3" json:"affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpactResponse) Reset() {
	*x = ImpactResponse{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpactResponse) ProtoMessage() {}

func (x *ImpactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpactResponse.ProtoReflect.Descriptor instead.
func (*ImpactResponse) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{15}
}

func (x *ImpactResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ImpactResponse) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *ImpactResponse) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *ImpactResponse) GetEdgeCount() int32 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

func (x *ImpactResponse) GetAffected() []*Location {
	if x != nil {
		return x.Affected
	}
	return nil
}

// AffectedRequest carries internal/query.Engine.Affected's two
// arguments unchanged. depth is passed straight through — validateDepth
// and clampAffectedDepth already bound/clamp it server-side for every
// caller (a DIFFERENT default than Impact's clampDepth — see
// clampAffectedDepth's doc comment — so this is deliberately its own
// message, not a reuse of ImpactRequest).
type AffectedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []string               `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffectedRequest) Reset() {
	*x = AffectedRequest{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffectedRequest) ProtoMessage() {}

func (x *AffectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffectedRequest.ProtoReflect.Descriptor instead.
func (*AffectedRequest) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{16}
}

func (x *AffectedRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *AffectedRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// AffectedResponse mirrors internal/query.AffectedResult's shape.
type AffectedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []string               `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	AffectedTests []*Location            `protobuf:"bytes,2,rep,name=affected_tests,json=affectedTests,proto3" json:"affected_tests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffectedResponse) Reset() {
	*x = AffectedResponse{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffectedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffectedResponse) ProtoMessage() {}

func (x *AffectedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffectedResponse.ProtoReflect.Descriptor instead.
func (*AffectedResponse) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{17}
}

func (x *AffectedResponse) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *AffectedResponse) GetAffectedTests() []*Location {
	if x != nil {
		return x.AffectedTests
	}
	return nil
}

// GetNodeDetailRequest carries internal/query.Engine.NodeDetail's three
// arguments unchanged. line is `optional` (proto3 presence tracking) so
// the wire can distinguish "no line hint" (line unset, mapping to the
// Engine's nil *int) from an explicit line 0 — collapsing the two would
// silently disable NODE-03's line-narrowing for a caller that means to
// pass line zero.
type GetNodeDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Line          *int32                 `protobuf:"varint,3,opt,name=line,proto3,oneof" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeDetailRequest) Reset() {
	*x = GetNodeDetailRequest{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeDetailRequest) ProtoMessage() {}

func (x *GetNodeDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeDetailRequest.ProtoReflect.Descriptor instead.
func (*GetNodeDetailRequest) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{18}
}

func (x *GetNodeDetailRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetNodeDetailRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *GetNodeDetailRequest) GetLine() int32 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	return 0
}

// NodeDefinition carries one multi-definition candidate (D-02). Every
// candidate in a GetNodeDetailResponse's definitions list carries its own
// node; detail_gathered distinguishes a candidate whose calls/called_by
// were actually fetched (one of the first uiMultiDefCap matches, see
// internal/uiserver/handlers.go) from one merely LISTED beyond the cap —
// for a listed-only candidate, calls and called_by are both empty and
// detail_gathered is false, so a client rendering "showing N of M" can
// tell which entries are complete without inferring it from emptiness
// alone (an in-cap candidate that genuinely calls and is called by
// nothing would otherwise be indistinguishable from an out-of-cap one).
type NodeDefinition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Node           *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Calls          []*Node                `protobuf:"bytes,2,rep,name=calls,proto3" json:"calls,omitempty"`
	CalledBy       []*Node                `protobuf:"bytes,3,rep,name=called_by,json=calledBy,proto3" json:"called_by,omitempty"`
	DetailGathered bool                   `protobuf:"varint,4,opt,name=detail_gathered,json=detailGathered,proto3" json:"detail_gathered,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeDefinition) Reset() {
	*x = NodeDefinition{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDefinition) ProtoMessage() {}

func (x *NodeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDefinition.ProtoReflect.Descriptor instead.
func (*NodeDefinition) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{19}
}

func (x *NodeDefinition) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeDefinition) GetCalls() []*Node {
	if x != nil {
		return x.Calls
	}
	return nil
}

func (x *NodeDefinition) GetCalledBy() []*Node {
	if x != nil {
		return x.CalledBy
	}
	return nil
}

func (x *NodeDefinition) GetDetailGathered() bool {
	if x != nil {
		return x.DetailGathered
	}
	return false
}

// GetNodeDetailResponse is the discriminated wire projection of
// internal/query.NodeDetail's three shapes (D-02): mode identifies which
// group of fields below is populated; every field belonging to the other
// two groups is left at its zero value, never an error. A client reading
// the wrong field for the current mode gets a zero value, not a panic or
// a wire error — this asymmetry is the whole reason mode exists as its
// own field rather than being inferred from which fields are non-empty.
//
//	mode                      | populated fields
//	--------------------------|--------------------------------------------
//	NODE_DETAIL_MODE_FILE       | path
//	NODE_DETAIL_MODE_SINGLE_DEF | node, calls, called_by
//	NODE_DETAIL_MODE_MULTI_DEF  | symbol, definitions, total_candidates
//
// total_candidates is the TRUE total candidate count
// (len(NodeDetail.Multi.Matches)) regardless of how many entries in
// definitions actually carry gathered detail — the UI's own
// uiMultiDefCap bounds gathering, never the reported total, so a client
// can always render "showing N of M" accurately.
type GetNodeDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Mode  NodeDetailMode         `protobuf:"varint,1,opt,name=mode,proto3,enum=codegraph.ui.v1.NodeDetailMode" json:"mode,omitempty"`
	// path is populated only in NODE_DETAIL_MODE_FILE.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// node, calls and called_by are populated only in
	// NODE_DETAIL_MODE_SINGLE_DEF.
	Node     *Node   `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	Calls    []*Node `protobuf:"bytes,4,rep,name=calls,proto3" json:"calls,omitempty"`
	CalledBy []*Node `protobuf:"bytes,5,rep,name=called_by,json=calledBy,proto3" json:"called_by,omitempty"`
	// symbol, definitions and total_candidates are populated only in
	// NODE_DETAIL_MODE_MULTI_DEF.
	Symbol          string            `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Definitions     []*NodeDefinition `protobuf:"bytes,7,rep,name=definitions,proto3" json:"definitions,omitempty"`
	TotalCandidates int32             `protobuf:"varint,8,opt,name=total_candidates,json=totalCandidates,proto3" json:"total_candidates,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetNodeDetailResponse) Reset() {
	*x = GetNodeDetailResponse{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeDetailResponse) ProtoMessage() {}

func (x *GetNodeDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeDetailResponse.ProtoReflect.Descriptor instead.
func (*GetNodeDetailResponse) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{20}
}

func (x *GetNodeDetailResponse) GetMode() NodeDetailMode {
	if x != nil {
		return x.Mode
	}
	return NodeDetailMode_NODE_DETAIL_MODE_UNSPECIFIED
}

func (x *GetNodeDetailResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetNodeDetailResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *GetNodeDetailResponse) GetCalls() []*Node {
	if x != nil {
		return x.Calls
	}
	return nil
}

func (x *GetNodeDetailResponse) GetCalledBy() []*Node {
	if x != nil {
		return x.CalledBy
	}
	return nil
}

func (x *GetNodeDetailResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetNodeDetailResponse) GetDefinitions() []*NodeDefinition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *GetNodeDetailResponse) GetTotalCandidates() int32 {
	if x != nil {
		return x.TotalCandidates
	}
	return 0
}

// ExploreRequest carries internal/query.Engine.ExploreDetail's two
// arguments unchanged. max_files is passed straight through:
// Engine.ExploreDetail's own validateMaxFiles/clampMaxFiles/H21 adaptive
// budget already bound it server-side for every caller, so this rpc adds
// no second copy of that rule.
type ExploreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	MaxFiles      int32                  `protobuf:"varint,2,opt,name=max_files,json=maxFiles,proto3" json:"max_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExploreRequest) Reset() {
	*x = ExploreRequest{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExploreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExploreRequest) ProtoMessage() {}

func (x *ExploreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExploreRequest.ProtoReflect.Descriptor instead.
func (*ExploreRequest) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{21}
}

func (x *ExploreRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExploreRequest) GetMaxFiles() int32 {
	if x != nil {
		return x.MaxFiles
	}
	return 0
}

// ExploreGroup is the wire projection of internal/query.ExploreFileGroup:
// one matched file's path plus every matched symbol defined in it, in
// ranked-match order. skeletonized mirrors whether this group's path is
// present in internal/query.ExploreResult.SkeletonFiles — a per-group
// boolean carries the same information a second client-side lookup would
// need, without requiring one.
type ExploreGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Symbols       []*Node                `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Skeletonized  bool                   `protobuf:"varint,3,opt,name=skeletonized,proto3" json:"skeletonized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExploreGroup) Reset() {
	*x = ExploreGroup{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExploreGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExploreGroup) ProtoMessage() {}

func (x *ExploreGroup) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExploreGroup.ProtoReflect.Descriptor instead.
func (*ExploreGroup) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{22}
}

func (x *ExploreGroup) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExploreGroup) GetSymbols() []*Node {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *ExploreGroup) GetSkeletonized() bool {
	if x != nil {
		return x.Skeletonized
	}
	return false
}

// BlastEntry is the wire projection of internal/query.ExploreBlast: one
// blast-radius bullet's matched symbol, its total caller count, and the
// distinct test files among those callers.
type BlastEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *Node                  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	CallerCount   int32                  `protobuf:"varint,2,opt,name=caller_count,json=callerCount,proto3" json:"caller_count,omitempty"`
	TestFiles     []string               `protobuf:"bytes,3,rep,name=test_files,json=testFiles,proto3" json:"test_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlastEntry) Reset() {
	*x = BlastEntry{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlastEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlastEntry) ProtoMessage() {}

func (x *BlastEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlastEntry.ProtoReflect.Descriptor instead.
func (*BlastEntry) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{23}
}

func (x *BlastEntry) GetSymbol() *Node {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *BlastEntry) GetCallerCount() int32 {
	if x != nil {
		return x.CallerCount
	}
	return 0
}

func (x *BlastEntry) GetTestFiles() []string {
	if x != nil {
		return x.TestFiles
	}
	return nil
}

// ExploreResponse is the wire projection of internal/query.ExploreResult
// (D-01, D-02). empty mirrors ExploreResult.Empty: a query matching
// nothing is a SUCCESSFUL response with empty=true and zero groups, never
// an error — Explore()'s five distinct "no results" pipeline stages all
// funnel through this one representation, and turning it into an error
// would make an ordinary "no results" indistinguishable from a genuine
// failure. When empty is true, groups and blasts are both empty and
// symbol_count is 0.
//
// Each ExploreGroup carries its OWN matched symbols and skeletonized
// flag — internal/query.ExploreResult.Sources is a map keyed by each
// group's own Path, which is exactly why the source that plan 01-10
// attaches lands on ExploreGroup itself (see this file's header comment)
// rather than as a single response-level blob: a response-level blob
// would lose which file each blob belongs to, and a parallel unkeyed
// list would make the association positional and therefore fragile.
type ExploreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Empty         bool                   `protobuf:"varint,2,opt,name=empty,proto3" json:"empty,omitempty"`
	Stale         bool                   `protobuf:"varint,3,opt,name=stale,proto3" json:"stale,omitempty"`
	SymbolCount   int32                  `protobuf:"varint,4,opt,name=symbol_count,json=symbolCount,proto3" json:"symbol_count,omitempty"`
	Groups        []*ExploreGroup        `protobuf:"bytes,5,rep,name=groups,proto3" json:"groups,omitempty"`
	Blasts        []*BlastEntry          `protobuf:"bytes,6,rep,name=blasts,proto3" json:"blasts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExploreResponse) Reset() {
	*x = ExploreResponse{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExploreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExploreResponse) ProtoMessage() {}

func (x *ExploreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExploreResponse.ProtoReflect.Descriptor instead.
func (*ExploreResponse) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{24}
}

func (x *ExploreResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExploreResponse) GetEmpty() bool {
	if x != nil {
		return x.Empty
	}
	return false
}

func (x *ExploreResponse) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *ExploreResponse) GetSymbolCount() int32 {
	if x != nil {
		return x.SymbolCount
	}
	return 0
}

func (x *ExploreResponse) GetGroups() []*ExploreGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ExploreResponse) GetBlasts() []*BlastEntry {
	if x != nil {
		return x.Blasts
	}
	return nil
}

// IndexingInProgress is the typed Connect error detail SRV-04's degrade
// path (D-14) attaches to a CodeUnavailable response when the graph
// store stays locked past graphstore.Open's retry budget. Reserved by
// this plan for that later plan (01-11) to populate; no rpc in this
// plan returns it yet.
type IndexingInProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message is a GENERIC, human-readable status string — never an OS
	// lock-file path, PID, or other host-local detail (Information
	// Disclosure risk to an unauthenticated loopback caller, T-01-06).
	// Absent (zero value: "") never occurs in practice: the later plan
	// that constructs this message always sets a non-empty generic
	// constant.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexingInProgress) Reset() {
	*x = IndexingInProgress{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexingInProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexingInProgress) ProtoMessage() {}

func (x *IndexingInProgress) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexingInProgress.ProtoReflect.Descriptor instead.
func (*IndexingInProgress) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{25}
}

func (x *IndexingInProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_uiproto_uiv1_ui_proto protoreflect.FileDescriptor

const file_internal_uiproto_uiv1_ui_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/uiproto/uiv1/ui.proto\x12\x0fcodegraph.ui.v1\"\xac\x03\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\x0equalified_name\x18\x04 \x01(\tR\rqualifiedName\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"start_line\x18\a \x01(\x05R\tstartLine\x12\x19\n" +
	"\bend_line\x18\b \x01(\x05R\aendLine\x12\x1b\n" +
	"\tstart_col\x18\t \x01(\x05R\bstartCol\x12\x17\n" +
	"\aend_col\x18\n" +
	" \x01(\x05R\x06endCol\x12\x1c\n" +
	"\tsignature\x18\v \x01(\tR\tsignature\x12\x1c\n" +
	"\tdocstring\x18\f \x01(\tR\tdocstring\x12\x1e\n" +
	"\n" +
	"visibility\x18\r \x01(\tR\n" +
	"visibility\x12\x1f\n" +
	"\vis_exported\x18\x0e \x01(\bR\n" +
	"isExported\x12\x1f\n" +
	"\vreturn_type\x18\x0f \x01(\tR\n" +
	"returnType\"n\n" +
	"\bLocation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"start_line\x18\x04 \x01(\x05R\tstartLine\"&\n" +
	"\x10GetStatusRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xe1\x01\n" +
	"\x11GetStatusResponse\x12 \n" +
	"\vinitialized\x18\x01 \x01(\bR\vinitialized\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"node_count\x18\x03 \x01(\x03R\tnodeCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x04 \x01(\x03R\tedgeCount\x12\x1d\n" +
	"\n" +
	"file_count\x18\x05 \x01(\x03R\tfileCount\x12\x14\n" +
	"\x05stale\x18\x06 \x01(\bR\x05stale\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\a \x01(\tR\tcommitSha\"M\n" +
	"\rSearchRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"I\n" +
	"\x0eSearchResponse\x127\n" +
	"\tlocations\x18\x01 \x03(\v2\x19.codegraph.ui.v1.LocationR\tlocations\"y\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"node_count\x18\x03 \x01(\x03R\tnodeCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x04 \x01(\x03R\tedgeCount\"\xa4\x01\n" +
	"\fFileTreeNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x129\n" +
	"\bchildren\x18\x05 \x03(\v2\x1d.codegraph.ui.v1.FileTreeNodeR\bchildren\"\x80\x01\n" +
	"\fFilesRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\tR\x03dir\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\x05R\x05depth\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\"\x8c\x01\n" +
	"\rFilesResponse\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x120\n" +
	"\x05files\x18\x02 \x03(\v2\x1a.codegraph.ui.v1.FileEntryR\x05files\x121\n" +
	"\x04tree\x18\x03 \x03(\v2\x1d.codegraph.ui.v1.FileTreeNodeR\x04tree\">\n" +
	"\x0eCallersRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"^\n" +
	"\x0fCallersResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x123\n" +
	"\acallers\x18\x02 \x03(\v2\x19.codegraph.ui.v1.LocationR\acallers\">\n" +
	"\x0eCalleesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"^\n" +
	"\x0fCalleesResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x123\n" +
	"\acallees\x18\x02 \x03(\v2\x19.codegraph.ui.v1.LocationR\acallees\"=\n" +
	"\rImpactRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"\xb3\x01\n" +
	"\x0eImpactResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\x12\x1d\n" +
	"\n" +
	"node_count\x18\x03 \x01(\x05R\tnodeCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x04 \x01(\x05R\tedgeCount\x125\n" +
	"\baffected\x18\x05 \x03(\v2\x19.codegraph.ui.v1.LocationR\baffected\"=\n" +
	"\x0fAffectedRequest\x12\x14\n" +
	"\x05files\x18\x01 \x03(\tR\x05files\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"j\n" +
	"\x10AffectedResponse\x12\x14\n" +
	"\x05files\x18\x01 \x03(\tR\x05files\x12@\n" +
	"\x0eaffected_tests\x18\x02 \x03(\v2\x19.codegraph.ui.v1.LocationR\raffectedTests\"d\n" +
	"\x14GetNodeDetailRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x17\n" +
	"\x04line\x18\x03 \x01(\x05H\x00R\x04line\x88\x01\x01B\a\n" +
	"\x05_line\"\xc5\x01\n" +
	"\x0eNodeDefinition\x12)\n" +
	"\x04node\x18\x01 \x01(\v2\x15.codegraph.ui.v1.NodeR\x04node\x12+\n" +
	"\x05calls\x18\x02 \x03(\v2\x15.codegraph.ui.v1.NodeR\x05calls\x122\n" +
	"\tcalled_by\x18\x03 \x03(\v2\x15.codegraph.ui.v1.NodeR\bcalledBy\x12'\n" +
	"\x0fdetail_gathered\x18\x04 \x01(\bR\x0edetailGathered\"\xf2\x02\n" +
	"\x15GetNodeDetailResponse\x123\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1f.codegraph.ui.v1.NodeDetailModeR\x04mode\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12)\n" +
	"\x04node\x18\x03 \x01(\v2\x15.codegraph.ui.v1.NodeR\x04node\x12+\n" +
	"\x05calls\x18\x04 \x03(\v2\x15.codegraph.ui.v1.NodeR\x05calls\x122\n" +
	"\tcalled_by\x18\x05 \x03(\v2\x15.codegraph.ui.v1.NodeR\bcalledBy\x12\x16\n" +
	"\x06symbol\x18\x06 \x01(\tR\x06symbol\x12A\n" +
	"\vdefinitions\x18\a \x03(\v2\x1f.codegraph.ui.v1.NodeDefinitionR\vdefinitions\x12)\n" +
	"\x10total_candidates\x18\b \x01(\x05R\x0ftotalCandidates\"C\n" +
	"\x0eExploreRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1b\n" +
	"\tmax_files\x18\x02 \x01(\x05R\bmaxFiles\"w\n" +
	"\fExploreGroup\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12/\n" +
	"\asymbols\x18\x02 \x03(\v2\x15.codegraph.ui.v1.NodeR\asymbols\x12\"\n" +
	"\fskeletonized\x18\x03 \x01(\bR\fskeletonized\"}\n" +
	"\n" +
	"BlastEntry\x12-\n" +
	"\x06symbol\x18\x01 \x01(\v2\x15.codegraph.ui.v1.NodeR\x06symbol\x12!\n" +
	"\fcaller_count\x18\x02 \x01(\x05R\vcallerCount\x12\x1d\n" +
	"\n" +
	"test_files\x18\x03 \x03(\tR\ttestFiles\"\xe2\x01\n" +
	"\x0fExploreResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05empty\x18\x02 \x01(\bR\x05empty\x12\x14\n" +
	"\x05stale\x18\x03 \x01(\bR\x05stale\x12!\n" +
	"\fsymbol_count\x18\x04 \x01(\x05R\vsymbolCount\x125\n" +
	"\x06groups\x18\x05 \x03(\v2\x1d.codegraph.ui.v1.ExploreGroupR\x06groups\x123\n" +
	"\x06blasts\x18\x06 \x03(\v2\x1b.codegraph.ui.v1.BlastEntryR\x06blasts\".\n" +
	"\x12IndexingInProgress\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*\x8e\x01\n" +
	"\x0eNodeDetailMode\x12 \n" +
	"\x1cNODE_DETAIL_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15NODE_DETAIL_MODE_FILE\x10\x01\x12\x1f\n" +
	"\x1bNODE_DETAIL_MODE_SINGLE_DEF\x10\x02\x12\x1e\n" +
	"\x1aNODE_DETAIL_MODE_MULTI_DEF\x10\x032\xd8\x05\n" +
	"\tUIService\x12R\n" +
	"\tGetStatus\x12!.codegraph.ui.v1.GetStatusRequest\x1a\".codegraph.ui.v1.GetStatusResponse\x12I\n" +
	"\x06Search\x12\x1e.codegraph.ui.v1.SearchRequest\x1a\x1f.codegraph.ui.v1.SearchResponse\x12F\n" +
	"\x05Files\x12\x1d.codegraph.ui.v1.FilesRequest\x1a\x1e.codegraph.ui.v1.FilesResponse\x12L\n" +
	"\aCallers\x12\x1f.codegraph.ui.v1.CallersRequest\x1a .codegraph.ui.v1.CallersResponse\x12L\n" +
	"\aCallees\x12\x1f.codegraph.ui.v1.CalleesRequest\x1a .codegraph.ui.v1.CalleesResponse\x12I\n" +
	"\x06Impact\x12\x1e.codegraph.ui.v1.ImpactRequest\x1a\x1f.codegraph.ui.v1.ImpactResponse\x12O\n" +
	"\bAffected\x12 .codegraph.ui.v1.AffectedRequest\x1a!.codegraph.ui.v1.AffectedResponse\x12^\n" +
	"\rGetNodeDetail\x12%.codegraph.ui.v1.GetNodeDetailRequest\x1a&.codegraph.ui.v1.GetNodeDetailResponse\x12L\n" +
	"\aExplore\x12\x1f.codegraph.ui.v1.ExploreRequest\x1a .codegraph.ui.v1.ExploreResponseB<Z:github.com/seanb4t/codegraph-go/internal/uiproto/uiv1;uiv1b\x06proto3"

var (
	file_internal_uiproto_uiv1_ui_proto_rawDescOnce sync.Once
	file_internal_uiproto_uiv1_ui_proto_rawDescData []byte
)

func file_internal_uiproto_uiv1_ui_proto_rawDescGZIP() []byte {
	file_internal_uiproto_uiv1_ui_proto_rawDescOnce.Do(func() {
		file_internal_uiproto_uiv1_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_uiproto_uiv1_ui_proto_rawDesc), len(file_internal_uiproto_uiv1_ui_proto_rawDesc)))
	})
	return file_internal_uiproto_uiv1_ui_proto_rawDescData
}

var file_internal_uiproto_uiv1_ui_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_uiproto_uiv1_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_internal_uiproto_uiv1_ui_proto_goTypes = []any{
	(NodeDetailMode)(0),           // 0: codegraph.ui.v1.NodeDetailMode
	(*Node)(nil),                  // 1: codegraph.ui.v1.Node
	(*Location)(nil),              // 2: codegraph.ui.v1.Location
	(*GetStatusRequest)(nil),      // 3: codegraph.ui.v1.GetStatusRequest
	(*GetStatusResponse)(nil),     // 4: codegraph.ui.v1.GetStatusResponse
	(*SearchRequest)(nil),         // 5: codegraph.ui.v1.SearchRequest
	(*SearchResponse)(nil),        // 6: codegraph.ui.v1.SearchResponse
	(*FileEntry)(nil),             // 7: codegraph.ui.v1.FileEntry
	(*FileTreeNode)(nil),          // 8: codegraph.ui.v1.FileTreeNode
	(*FilesRequest)(nil),          // 9: codegraph.ui.v1.FilesRequest
	(*FilesResponse)(nil),         // 10: codegraph.ui.v1.FilesResponse
	(*CallersRequest)(nil),        // 11: codegraph.ui.v1.CallersRequest
	(*CallersResponse)(nil),       // 12: codegraph.ui.v1.CallersResponse
	(*CalleesRequest)(nil),        // 13: codegraph.ui.v1.CalleesRequest
	(*CalleesResponse)(nil),       // 14: codegraph.ui.v1.CalleesResponse
	(*ImpactRequest)(nil),         // 15: codegraph.ui.v1.ImpactRequest
	(*ImpactResponse)(nil),        // 16: codegraph.ui.v1.ImpactResponse
	(*AffectedRequest)(nil),       // 17: codegraph.ui.v1.AffectedRequest
	(*AffectedResponse)(nil),      // 18: codegraph.ui.v1.AffectedResponse
	(*GetNodeDetailRequest)(nil),  // 19: codegraph.ui.v1.GetNodeDetailRequest
	(*NodeDefinition)(nil),        // 20: codegraph.ui.v1.NodeDefinition
	(*GetNodeDetailResponse)(nil), // 21: codegraph.ui.v1.GetNodeDetailResponse
	(*ExploreRequest)(nil),        // 22: codegraph.ui.v1.ExploreRequest
	(*ExploreGroup)(nil),          // 23: codegraph.ui.v1.ExploreGroup
	(*BlastEntry)(nil),            // 24: codegraph.ui.v1.BlastEntry
	(*ExploreResponse)(nil),       // 25: codegraph.ui.v1.ExploreResponse
	(*IndexingInProgress)(nil),    // 26: codegraph.ui.v1.IndexingInProgress
}
var file_internal_uiproto_uiv1_ui_proto_depIdxs = []int32{
	2,  // 0: codegraph.ui.v1.SearchResponse.locations:type_name -> codegraph.ui.v1.Location
	8,  // 1: codegraph.ui.v1.FileTreeNode.children:type_name -> codegraph.ui.v1.FileTreeNode
	7,  // 2: codegraph.ui.v1.FilesResponse.files:type_name -> codegraph.ui.v1.FileEntry
	8,  // 3: codegraph.ui.v1.FilesResponse.tree:type_name -> codegraph.ui.v1.FileTreeNode
	2,  // 4: codegraph.ui.v1.CallersResponse.callers:type_name -> codegraph.ui.v1.Location
	2,  // 5: codegraph.ui.v1.CalleesResponse.callees:type_name -> codegraph.ui.v1.Location
	2,  // 6: codegraph.ui.v1.ImpactResponse.affected:type_name -> codegraph.ui.v1.Location
	2,  // 7: codegraph.ui.v1.AffectedResponse.affected_tests:type_name -> codegraph.ui.v1.Location
	1,  // 8: codegraph.ui.v1.NodeDefinition.node:type_name -> codegraph.ui.v1.Node
	1,  // 9: codegraph.ui.v1.NodeDefinition.calls:type_name -> codegraph.ui.v1.Node
	1,  // 10: codegraph.ui.v1.NodeDefinition.called_by:type_name -> codegraph.ui.v1.Node
	0,  // 11: codegraph.ui.v1.GetNodeDetailResponse.mode:type_name -> codegraph.ui.v1.NodeDetailMode
	1,  // 12: codegraph.ui.v1.GetNodeDetailResponse.node:type_name -> codegraph.ui.v1.Node
	1,  // 13: codegraph.ui.v1.GetNodeDetailResponse.calls:type_name -> codegraph.ui.v1.Node
	1,  // 14: codegraph.ui.v1.GetNodeDetailResponse.called_by:type_name -> codegraph.ui.v1.Node
	20, // 15: codegraph.ui.v1.GetNodeDetailResponse.definitions:type_name -> codegraph.ui.v1.NodeDefinition
	1,  // 16: codegraph.ui.v1.ExploreGroup.symbols:type_name -> codegraph.ui.v1.Node
	1,  // 17: codegraph.ui.v1.BlastEntry.symbol:type_name -> codegraph.ui.v1.Node
	23, // 18: codegraph.ui.v1.ExploreResponse.groups:type_name -> codegraph.ui.v1.ExploreGroup
	24, // 19: codegraph.ui.v1.ExploreResponse.blasts:type_name -> codegraph.ui.v1.BlastEntry
	3,  // 20: codegraph.ui.v1.UIService.GetStatus:input_type -> codegraph.ui.v1.GetStatusRequest
	5,  // 21: codegraph.ui.v1.UIService.Search:input_type -> codegraph.ui.v1.SearchRequest
	9,  // 22: codegraph.ui.v1.UIService.Files:input_type -> codegraph.ui.v1.FilesRequest
	11, // 23: codegraph.ui.v1.UIService.Callers:input_type -> codegraph.ui.v1.CallersRequest
	13, // 24: codegraph.ui.v1.UIService.Callees:input_type -> codegraph.ui.v1.CalleesRequest
	15, // 25: codegraph.ui.v1.UIService.Impact:input_type -> codegraph.ui.v1.ImpactRequest
	17, // 26: codegraph.ui.v1.UIService.Affected:input_type -> codegraph.ui.v1.AffectedRequest
	19, // 27: codegraph.ui.v1.UIService.GetNodeDetail:input_type -> codegraph.ui.v1.GetNodeDetailRequest
	22, // 28: codegraph.ui.v1.UIService.Explore:input_type -> codegraph.ui.v1.ExploreRequest
	4,  // 29: codegraph.ui.v1.UIService.GetStatus:output_type -> codegraph.ui.v1.GetStatusResponse
	6,  // 30: codegraph.ui.v1.UIService.Search:output_type -> codegraph.ui.v1.SearchResponse
	10, // 31: codegraph.ui.v1.UIService.Files:output_type -> codegraph.ui.v1.FilesResponse
	12, // 32: codegraph.ui.v1.UIService.Callers:output_type -> codegraph.ui.v1.CallersResponse
	14, // 33: codegraph.ui.v1.UIService.Callees:output_type -> codegraph.ui.v1.CalleesResponse
	16, // 34: codegraph.ui.v1.UIService.Impact:output_type -> codegraph.ui.v1.ImpactResponse
	18, // 35: codegraph.ui.v1.UIService.Affected:output_type -> codegraph.ui.v1.AffectedResponse
	21, // 36: codegraph.ui.v1.UIService.GetNodeDetail:output_type -> codegraph.ui.v1.GetNodeDetailResponse
	25, // 37: codegraph.ui.v1.UIService.Explore:output_type -> codegraph.ui.v1.ExploreResponse
	29, // [29:38] is the sub-list for method output_type
	20, // [20:29] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_internal_uiproto_uiv1_ui_proto_init() }
func file_internal_uiproto_uiv1_ui_proto_init() {
	if File_internal_uiproto_uiv1_ui_proto != nil {
		return
	}
	file_internal_uiproto_uiv1_ui_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_uiproto_uiv1_ui_proto_rawDesc), len(file_internal_uiproto_uiv1_ui_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_uiproto_uiv1_ui_proto_goTypes,
		DependencyIndexes: file_internal_uiproto_uiv1_ui_proto_depIdxs,
		EnumInfos:         file_internal_uiproto_uiv1_ui_proto_enumTypes,
		MessageInfos:      file_internal_uiproto_uiv1_ui_proto_msgTypes,
	}.Build()
	File_internal_uiproto_uiv1_ui_proto = out.File
	file_internal_uiproto_uiv1_ui_proto_goTypes = nil
	file_internal_uiproto_uiv1_ui_proto_depIdxs = nil
}
