// Package codegraph.ui.v1 defines codegraph ui's wire protocol: a Connect
// RPC service over the repository's own read-only internal/query.Engine
// (RPC-01, RPC-02). This is a SECOND proto surface, independent of
// internal/schema/graph.proto's on-disk graph-store record format — this
// package never appears on disk, only on the loopback wire.
//
// Additive-only discipline (D-02a, inherited from internal/schema):
// within this package, a field number is never renumbered and never
// reused. When a field is retired, its number is added to a `reserved`
// clause instead of being deleted or repurposed.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/uiproto/uiv1/ui.proto

package uiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetStatusRequest is presently empty of consulted fields — v1's server
// binds exactly one repository at startup (uiserver.Options.RepoPath, an
// unwired field per D-08) and every rpc reports on that repository.
type GetStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path is RESERVED for a future milestone where one server process
	// answers for more than one repository; the v1 handler does not read
	// it — every response reports on the server's own configured
	// RepoPath regardless of this field's value. Declared now, rather
	// than left for a later field-number addition, so the wire shape is
	// stable before any client depends on it.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatusRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// GetStatusResponse is the uiv1 projection of internal/query.StatusResult
// (D-06): a bounded subset sufficient for this tracer's health check,
// not the full CLI `status --json` shape. The mapping table lives in
// internal/uiserver/handlers.go's GetStatus doc comment.
type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// initialized mirrors StatusResult.Initialized: true whenever this
	// response was produced from a successfully opened Engine. Absent
	// (zero value: false) has no meaning yet in this plan — SRV-04's
	// degrade path (D-16, a later plan) is the first caller that can
	// legitimately answer with initialized=false from a locked store.
	Initialized bool `protobuf:"varint,1,opt,name=initialized,proto3" json:"initialized,omitempty"`
	// version mirrors StatusResult.Version — the schema version string
	// (fmt.Sprintf("%d", schema.SchemaVersion)), not a codegraph-go
	// release version (D-06, status.go's mapping table).
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// node_count mirrors StatusResult.NodeCount, a live graphstore.Reader
	// scan result. Absent (zero value: 0) means the store reported no
	// nodes, not "unknown" — this plan's GetStatus never returns a
	// zero-valued node_count for any other reason, since a failed Engine
	// open never reaches message construction in this plan.
	NodeCount int64 `protobuf:"varint,3,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	// edge_count mirrors StatusResult.EdgeCount, the same discipline as
	// node_count.
	EdgeCount int64 `protobuf:"varint,4,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	// file_count mirrors StatusResult.FileCount, the same discipline as
	// node_count.
	FileCount int64 `protobuf:"varint,5,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	// stale mirrors StatusResult.Stale (D-04a): true when a sync is
	// pending (the watcher/daemon signal file exists, or the newest
	// on-disk source mtime is newer than the last recorded sync).
	Stale         bool `protobuf:"varint,6,opt,name=stale,proto3" json:"stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetNodeCount() int64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *GetStatusResponse) GetEdgeCount() int64 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

func (x *GetStatusResponse) GetFileCount() int64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *GetStatusResponse) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

// IndexingInProgress is the typed Connect error detail SRV-04's degrade
// path (D-14) attaches to a CodeUnavailable response when the graph
// store stays locked past graphstore.Open's retry budget. Reserved by
// this plan for that later plan (01-11) to populate; no rpc in this
// plan returns it yet.
type IndexingInProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message is a GENERIC, human-readable status string — never an OS
	// lock-file path, PID, or other host-local detail (Information
	// Disclosure risk to an unauthenticated loopback caller, T-01-06).
	// Absent (zero value: "") never occurs in practice: the later plan
	// that constructs this message always sets a non-empty generic
	// constant.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexingInProgress) Reset() {
	*x = IndexingInProgress{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexingInProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexingInProgress) ProtoMessage() {}

func (x *IndexingInProgress) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexingInProgress.ProtoReflect.Descriptor instead.
func (*IndexingInProgress) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{2}
}

func (x *IndexingInProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_uiproto_uiv1_ui_proto protoreflect.FileDescriptor

const file_internal_uiproto_uiv1_ui_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/uiproto/uiv1/ui.proto\x12\x0fcodegraph.ui.v1\"&\n" +
	"\x10GetStatusRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xc2\x01\n" +
	"\x11GetStatusResponse\x12 \n" +
	"\vinitialized\x18\x01 \x01(\bR\vinitialized\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"node_count\x18\x03 \x01(\x03R\tnodeCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x04 \x01(\x03R\tedgeCount\x12\x1d\n" +
	"\n" +
	"file_count\x18\x05 \x01(\x03R\tfileCount\x12\x14\n" +
	"\x05stale\x18\x06 \x01(\bR\x05stale\".\n" +
	"\x12IndexingInProgress\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2_\n" +
	"\tUIService\x12R\n" +
	"\tGetStatus\x12!.codegraph.ui.v1.GetStatusRequest\x1a\".codegraph.ui.v1.GetStatusResponseB<Z:github.com/seanb4t/codegraph-go/internal/uiproto/uiv1;uiv1b\x06proto3"

var (
	file_internal_uiproto_uiv1_ui_proto_rawDescOnce sync.Once
	file_internal_uiproto_uiv1_ui_proto_rawDescData []byte
)

func file_internal_uiproto_uiv1_ui_proto_rawDescGZIP() []byte {
	file_internal_uiproto_uiv1_ui_proto_rawDescOnce.Do(func() {
		file_internal_uiproto_uiv1_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_uiproto_uiv1_ui_proto_rawDesc), len(file_internal_uiproto_uiv1_ui_proto_rawDesc)))
	})
	return file_internal_uiproto_uiv1_ui_proto_rawDescData
}

var file_internal_uiproto_uiv1_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_uiproto_uiv1_ui_proto_goTypes = []any{
	(*GetStatusRequest)(nil),   // 0: codegraph.ui.v1.GetStatusRequest
	(*GetStatusResponse)(nil),  // 1: codegraph.ui.v1.GetStatusResponse
	(*IndexingInProgress)(nil), // 2: codegraph.ui.v1.IndexingInProgress
}
var file_internal_uiproto_uiv1_ui_proto_depIdxs = []int32{
	0, // 0: codegraph.ui.v1.UIService.GetStatus:input_type -> codegraph.ui.v1.GetStatusRequest
	1, // 1: codegraph.ui.v1.UIService.GetStatus:output_type -> codegraph.ui.v1.GetStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_uiproto_uiv1_ui_proto_init() }
func file_internal_uiproto_uiv1_ui_proto_init() {
	if File_internal_uiproto_uiv1_ui_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_uiproto_uiv1_ui_proto_rawDesc), len(file_internal_uiproto_uiv1_ui_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_uiproto_uiv1_ui_proto_goTypes,
		DependencyIndexes: file_internal_uiproto_uiv1_ui_proto_depIdxs,
		MessageInfos:      file_internal_uiproto_uiv1_ui_proto_msgTypes,
	}.Build()
	File_internal_uiproto_uiv1_ui_proto = out.File
	file_internal_uiproto_uiv1_ui_proto_goTypes = nil
	file_internal_uiproto_uiv1_ui_proto_depIdxs = nil
}
