// Package codegraph.ui.v1 defines codegraph ui's wire protocol: a Connect
// RPC service over the repository's own read-only internal/query.Engine
// (RPC-01, RPC-02). This is a SECOND proto surface, independent of
// internal/schema/graph.proto's on-disk graph-store record format — this
// package never appears on disk, only on the loopback wire.
//
// Additive-only discipline (D-02a, inherited from internal/schema):
// within this package, a field number is never renumbered and never
// reused. When a field is retired, its number is added to a `reserved`
// clause instead of being deleted or repurposed.
//
// Deliberate omission — Query vs Search (plan 01-08): internal/query.Engine
// exposes both Query (full node records for an exact name/kind match) and
// Search (the lightweight Location-only projection of the same match).
// Only Search is exposed here. Query's fuller shape — calls, called-by, and
// the multi-definition candidate set — is strictly subsumed by plan
// 01-09's GetNodeDetail rpc, which covers node lookup; Search covers
// discovery. Exposing both Query and Search on the wire would give the UI
// two overlapping name-lookup rpcs with different result shapes and no
// rule about which to reach for. This service's contract is "every read
// the UI needs", not "every exported method on Engine" — this is that
// contract applied, not an oversight.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/uiproto/uiv1/ui.proto

package uiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node is the shared wire projection of a graph symbol record — the
// fields a UI view actually renders, mirroring internal/schema/graph.proto's
// Node message field-for-field (minus its reserved 50-59 annotation
// range, which has no consumer yet on either surface). Defined once here
// and reused across every response that needs a full node rather than a
// bare Location, so Phases 3-6 never have to reconcile divergent
// per-response node shapes for the same underlying record.
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	QualifiedName string                 `protobuf:"bytes,4,opt,name=qualified_name,json=qualifiedName,proto3" json:"qualified_name,omitempty"`
	FilePath      string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	StartLine     int32                  `protobuf:"varint,7,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine       int32                  `protobuf:"varint,8,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	StartCol      int32                  `protobuf:"varint,9,opt,name=start_col,json=startCol,proto3" json:"start_col,omitempty"`
	EndCol        int32                  `protobuf:"varint,10,opt,name=end_col,json=endCol,proto3" json:"end_col,omitempty"`
	Signature     string                 `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	Docstring     string                 `protobuf:"bytes,12,opt,name=docstring,proto3" json:"docstring,omitempty"`
	Visibility    string                 `protobuf:"bytes,13,opt,name=visibility,proto3" json:"visibility,omitempty"`
	IsExported    bool                   `protobuf:"varint,14,opt,name=is_exported,json=isExported,proto3" json:"is_exported,omitempty"`
	ReturnType    string                 `protobuf:"bytes,15,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetQualifiedName() string {
	if x != nil {
		return x.QualifiedName
	}
	return ""
}

func (x *Node) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Node) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Node) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *Node) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *Node) GetStartCol() int32 {
	if x != nil {
		return x.StartCol
	}
	return 0
}

func (x *Node) GetEndCol() int32 {
	if x != nil {
		return x.EndCol
	}
	return 0
}

func (x *Node) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Node) GetDocstring() string {
	if x != nil {
		return x.Docstring
	}
	return ""
}

func (x *Node) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Node) GetIsExported() bool {
	if x != nil {
		return x.IsExported
	}
	return false
}

func (x *Node) GetReturnType() string {
	if x != nil {
		return x.ReturnType
	}
	return ""
}

// Location is the shared wire projection of internal/query.Location — a
// lightweight name/kind/file/line-only reference, with no source body or
// signature. Every traversal rpc's repeated result (Search, Callers,
// Callees, Impact, Affected) reuses this one message rather than a
// per-rpc variant.
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	StartLine     int32                  `protobuf:"varint,4,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Location) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Location) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

// GetStatusRequest is presently empty of consulted fields — v1's server
// binds exactly one repository at startup (uiserver.Options.RepoPath, an
// unwired field per D-08) and every rpc reports on that repository.
type GetStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path is RESERVED for a future milestone where one server process
	// answers for more than one repository; the v1 handler does not read
	// it — every response reports on the server's own configured
	// RepoPath regardless of this field's value. Declared now, rather
	// than left for a later field-number addition, so the wire shape is
	// stable before any client depends on it.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// GetStatusResponse is the uiv1 projection of internal/query.StatusResult
// (D-06): a bounded subset sufficient for this tracer's health check,
// not the full CLI `status --json` shape. The mapping table lives in
// internal/uiserver/handlers.go's GetStatus doc comment.
type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// initialized mirrors StatusResult.Initialized: true whenever this
	// response was produced from a successfully opened Engine. Absent
	// (zero value: false) has no meaning yet in this plan — SRV-04's
	// degrade path (D-16, a later plan) is the first caller that can
	// legitimately answer with initialized=false from a locked store.
	Initialized bool `protobuf:"varint,1,opt,name=initialized,proto3" json:"initialized,omitempty"`
	// version mirrors StatusResult.Version — the schema version string
	// (fmt.Sprintf("%d", schema.SchemaVersion)), not a codegraph-go
	// release version (D-06, status.go's mapping table).
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// node_count mirrors StatusResult.NodeCount, a live graphstore.Reader
	// scan result. Absent (zero value: 0) means the store reported no
	// nodes, not "unknown" — this plan's GetStatus never returns a
	// zero-valued node_count for any other reason, since a failed Engine
	// open never reaches message construction in this plan.
	NodeCount int64 `protobuf:"varint,3,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	// edge_count mirrors StatusResult.EdgeCount, the same discipline as
	// node_count.
	EdgeCount int64 `protobuf:"varint,4,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	// file_count mirrors StatusResult.FileCount, the same discipline as
	// node_count.
	FileCount int64 `protobuf:"varint,5,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	// stale mirrors StatusResult.Stale (D-04a): true when a sync is
	// pending (the watcher/daemon signal file exists, or the newest
	// on-disk source mtime is newer than the last recorded sync).
	Stale bool `protobuf:"varint,6,opt,name=stale,proto3" json:"stale,omitempty"`
	// commit_sha (ENG-04, D-05/D-06) is the git commit this graph was
	// indexed at, read through (*query.Engine).IndexMeta and
	// schema.IndexedCommitSHA. Empty means the graph predates Meta field 8
	// (a pre-upgrade graph) or the index was built outside a git checkout
	// — both cases are "unknown", never an error, and the client must
	// render "unknown" rather than treating an empty value as a failure.
	//
	// Field numbers 8 and 9 on this message are ALREADY ALLOCATED to plan
	// 01-11's store_exists and indexing_in_progress fields (D-14/D-16's
	// degrade path) and MUST NOT be assigned here or by any other plan — a
	// numbering collision between two plans sharing this phase is exactly
	// what D-02a's additive-only, never-renumbered discipline exists to
	// prevent.
	CommitSha     string `protobuf:"bytes,7,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetNodeCount() int64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *GetStatusResponse) GetEdgeCount() int64 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

func (x *GetStatusResponse) GetFileCount() int64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *GetStatusResponse) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *GetStatusResponse) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

// SearchRequest carries internal/query.Engine.Search's three arguments
// unchanged. limit is passed straight through: validateLimit and MaxLimit
// already bound it server-side for every caller, so this rpc adds no
// second copy of that rule that could drift from the Engine's own.
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{4}
}

func (x *SearchRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *SearchRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SearchResponse carries Search's Location matches, in the same order
// Engine.Search returns them.
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

// IndexingInProgress is the typed Connect error detail SRV-04's degrade
// path (D-14) attaches to a CodeUnavailable response when the graph
// store stays locked past graphstore.Open's retry budget. Reserved by
// this plan for that later plan (01-11) to populate; no rpc in this
// plan returns it yet.
type IndexingInProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message is a GENERIC, human-readable status string — never an OS
	// lock-file path, PID, or other host-local detail (Information
	// Disclosure risk to an unauthenticated loopback caller, T-01-06).
	// Absent (zero value: "") never occurs in practice: the later plan
	// that constructs this message always sets a non-empty generic
	// constant.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexingInProgress) Reset() {
	*x = IndexingInProgress{}
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexingInProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexingInProgress) ProtoMessage() {}

func (x *IndexingInProgress) ProtoReflect() protoreflect.Message {
	mi := &file_internal_uiproto_uiv1_ui_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexingInProgress.ProtoReflect.Descriptor instead.
func (*IndexingInProgress) Descriptor() ([]byte, []int) {
	return file_internal_uiproto_uiv1_ui_proto_rawDescGZIP(), []int{6}
}

func (x *IndexingInProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_uiproto_uiv1_ui_proto protoreflect.FileDescriptor

const file_internal_uiproto_uiv1_ui_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/uiproto/uiv1/ui.proto\x12\x0fcodegraph.ui.v1\"\xac\x03\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\x0equalified_name\x18\x04 \x01(\tR\rqualifiedName\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"start_line\x18\a \x01(\x05R\tstartLine\x12\x19\n" +
	"\bend_line\x18\b \x01(\x05R\aendLine\x12\x1b\n" +
	"\tstart_col\x18\t \x01(\x05R\bstartCol\x12\x17\n" +
	"\aend_col\x18\n" +
	" \x01(\x05R\x06endCol\x12\x1c\n" +
	"\tsignature\x18\v \x01(\tR\tsignature\x12\x1c\n" +
	"\tdocstring\x18\f \x01(\tR\tdocstring\x12\x1e\n" +
	"\n" +
	"visibility\x18\r \x01(\tR\n" +
	"visibility\x12\x1f\n" +
	"\vis_exported\x18\x0e \x01(\bR\n" +
	"isExported\x12\x1f\n" +
	"\vreturn_type\x18\x0f \x01(\tR\n" +
	"returnType\"n\n" +
	"\bLocation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"start_line\x18\x04 \x01(\x05R\tstartLine\"&\n" +
	"\x10GetStatusRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xe1\x01\n" +
	"\x11GetStatusResponse\x12 \n" +
	"\vinitialized\x18\x01 \x01(\bR\vinitialized\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"node_count\x18\x03 \x01(\x03R\tnodeCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x04 \x01(\x03R\tedgeCount\x12\x1d\n" +
	"\n" +
	"file_count\x18\x05 \x01(\x03R\tfileCount\x12\x14\n" +
	"\x05stale\x18\x06 \x01(\bR\x05stale\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\a \x01(\tR\tcommitSha\"M\n" +
	"\rSearchRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"I\n" +
	"\x0eSearchResponse\x127\n" +
	"\tlocations\x18\x01 \x03(\v2\x19.codegraph.ui.v1.LocationR\tlocations\".\n" +
	"\x12IndexingInProgress\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xaa\x01\n" +
	"\tUIService\x12R\n" +
	"\tGetStatus\x12!.codegraph.ui.v1.GetStatusRequest\x1a\".codegraph.ui.v1.GetStatusResponse\x12I\n" +
	"\x06Search\x12\x1e.codegraph.ui.v1.SearchRequest\x1a\x1f.codegraph.ui.v1.SearchResponseB<Z:github.com/seanb4t/codegraph-go/internal/uiproto/uiv1;uiv1b\x06proto3"

var (
	file_internal_uiproto_uiv1_ui_proto_rawDescOnce sync.Once
	file_internal_uiproto_uiv1_ui_proto_rawDescData []byte
)

func file_internal_uiproto_uiv1_ui_proto_rawDescGZIP() []byte {
	file_internal_uiproto_uiv1_ui_proto_rawDescOnce.Do(func() {
		file_internal_uiproto_uiv1_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_uiproto_uiv1_ui_proto_rawDesc), len(file_internal_uiproto_uiv1_ui_proto_rawDesc)))
	})
	return file_internal_uiproto_uiv1_ui_proto_rawDescData
}

var file_internal_uiproto_uiv1_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_uiproto_uiv1_ui_proto_goTypes = []any{
	(*Node)(nil),               // 0: codegraph.ui.v1.Node
	(*Location)(nil),           // 1: codegraph.ui.v1.Location
	(*GetStatusRequest)(nil),   // 2: codegraph.ui.v1.GetStatusRequest
	(*GetStatusResponse)(nil),  // 3: codegraph.ui.v1.GetStatusResponse
	(*SearchRequest)(nil),      // 4: codegraph.ui.v1.SearchRequest
	(*SearchResponse)(nil),     // 5: codegraph.ui.v1.SearchResponse
	(*IndexingInProgress)(nil), // 6: codegraph.ui.v1.IndexingInProgress
}
var file_internal_uiproto_uiv1_ui_proto_depIdxs = []int32{
	1, // 0: codegraph.ui.v1.SearchResponse.locations:type_name -> codegraph.ui.v1.Location
	2, // 1: codegraph.ui.v1.UIService.GetStatus:input_type -> codegraph.ui.v1.GetStatusRequest
	4, // 2: codegraph.ui.v1.UIService.Search:input_type -> codegraph.ui.v1.SearchRequest
	3, // 3: codegraph.ui.v1.UIService.GetStatus:output_type -> codegraph.ui.v1.GetStatusResponse
	5, // 4: codegraph.ui.v1.UIService.Search:output_type -> codegraph.ui.v1.SearchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_uiproto_uiv1_ui_proto_init() }
func file_internal_uiproto_uiv1_ui_proto_init() {
	if File_internal_uiproto_uiv1_ui_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_uiproto_uiv1_ui_proto_rawDesc), len(file_internal_uiproto_uiv1_ui_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_uiproto_uiv1_ui_proto_goTypes,
		DependencyIndexes: file_internal_uiproto_uiv1_ui_proto_depIdxs,
		MessageInfos:      file_internal_uiproto_uiv1_ui_proto_msgTypes,
	}.Build()
	File_internal_uiproto_uiv1_ui_proto = out.File
	file_internal_uiproto_uiv1_ui_proto_goTypes = nil
	file_internal_uiproto_uiv1_ui_proto_depIdxs = nil
}
