// Package codegraph.v1 defines the schema-versioned record format for the
// codegraph-go graph store (D-02). Every message follows an additive-only
// evolution discipline (D-02a): field numbers are never renumbered or
// reused. When a field is retired, its number is added to a `reserved`
// clause instead of being deleted outright. Each of Node and Edge reserves
// a contiguous field-number range for post-v1 annotations (embedding
// vectors, community/cluster assignments) so those fields land at a
// pre-agreed number instead of "whatever's next" — this is the physical
// mechanism behind ARCH-01's forward-compatibility guarantee.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/schema/graph.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node is a single symbol record (function, type, method, etc.) extracted
// from a source file.
//
// NOTE: field names/types are designed against the TS `.codegraph/` DDL
// captured in Plan 01-04. If 01-04 has not landed by the time this is read,
// reconcile these fields against the captured DDL once it is available —
// additively only, per D-02a.
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	QualifiedName string                 `protobuf:"bytes,4,opt,name=qualified_name,json=qualifiedName,proto3" json:"qualified_name,omitempty"`
	FilePath      string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	StartLine     int32                  `protobuf:"varint,7,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine       int32                  `protobuf:"varint,8,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	StartCol      int32                  `protobuf:"varint,9,opt,name=start_col,json=startCol,proto3" json:"start_col,omitempty"`
	EndCol        int32                  `protobuf:"varint,10,opt,name=end_col,json=endCol,proto3" json:"end_col,omitempty"`
	// signature is the extractor-rendered parameter/return signature string
	// (e.g. "func(a int, b string) error"). Additive Go-parity field (D-03);
	// written by the Phase 2 goextract symbol pass.
	Signature string `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	// docstring is the leading comment/doc block attached to the symbol, as
	// captured verbatim by the extractor. Additive Go-parity field (D-03);
	// written by the Phase 2 goextract symbol pass.
	Docstring string `protobuf:"bytes,12,opt,name=docstring,proto3" json:"docstring,omitempty"`
	// visibility is the language-level access modifier ("public", "private",
	// "package", etc.) as classified by the extractor. Additive Go-parity
	// field (D-03); written by the Phase 2 goextract symbol pass.
	Visibility string `protobuf:"bytes,13,opt,name=visibility,proto3" json:"visibility,omitempty"`
	// is_exported reports whether the symbol crosses the package/module
	// boundary (Go: identifier starts uppercase). Additive Go-parity field
	// (D-03); written by the Phase 2 goextract symbol pass.
	IsExported bool `protobuf:"varint,14,opt,name=is_exported,json=isExported,proto3" json:"is_exported,omitempty"`
	// return_type is the extractor-rendered return type string, when the
	// symbol kind has one (function/method). Additive Go-parity field
	// (D-03); written by the Phase 2 goextract symbol pass.
	ReturnType    string `protobuf:"bytes,15,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_internal_schema_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_internal_schema_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_internal_schema_graph_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetQualifiedName() string {
	if x != nil {
		return x.QualifiedName
	}
	return ""
}

func (x *Node) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Node) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Node) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *Node) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *Node) GetStartCol() int32 {
	if x != nil {
		return x.StartCol
	}
	return 0
}

func (x *Node) GetEndCol() int32 {
	if x != nil {
		return x.EndCol
	}
	return 0
}

func (x *Node) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Node) GetDocstring() string {
	if x != nil {
		return x.Docstring
	}
	return ""
}

func (x *Node) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Node) GetIsExported() bool {
	if x != nil {
		return x.IsExported
	}
	return false
}

func (x *Node) GetReturnType() string {
	if x != nil {
		return x.ReturnType
	}
	return ""
}

// Edge is a directed relationship between two Node ids (calls, imports,
// implements, etc.).
type Edge struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Source string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Kind   string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// Optional call-site coordinates. Per RESEARCH Pitfall 2 / Open Question
	// 3: the Pebble edge KEY (`e/<src>/<kind>/<dst>`, D-03) intentionally
	// omits line/col today, so two call sites between the same (source,
	// kind, target) collapse to one stored edge. That key-identity decision
	// is deferred to Phase 2 extractor design — this record must still be
	// able to CARRY line/col so a future key-shape change (or an
	// annotation/audit trail) doesn't lose the data that's available at
	// extraction time.
	Line int32 `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Col  int32 `protobuf:"varint,5,opt,name=col,proto3" json:"col,omitempty"`
	// provenance records how this edge was derived. Phase 2 writes only
	// ground-truth values ("ast" or empty) per D-03a; "heuristic" provenance
	// (fuzzy/inferred edges) is Phase 5's addition, not written here.
	Provenance string `protobuf:"bytes,6,opt,name=provenance,proto3" json:"provenance,omitempty"`
	// metadata is an open extension bag for edge-kind-specific extractor
	// annotations that do not warrant their own field yet. Additive Go-parity
	// field (D-03).
	Metadata      map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_internal_schema_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_internal_schema_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_internal_schema_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Edge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Edge) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Edge) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Edge) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Edge) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *Edge) GetProvenance() string {
	if x != nil {
		return x.Provenance
	}
	return ""
}

func (x *Edge) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// File is a per-source-file record: identity, content hash, and
// aggregate counts for the symbols/edges attributed to it.
type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// content_hash MUST be a collision-resistant hash (SHA-256 — see
	// Security Domain V6 in 01-RESEARCH.md), never a weak hash like MD5.
	// The hash computation itself lands with the Phase 2 indexer; this
	// field only defines its storage shape.
	ContentHash string `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Language    string `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	NodeCount   int64  `protobuf:"varint,4,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	EdgeCount   int64  `protobuf:"varint,5,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	// errors records per-file extraction failures (e.g. oversized or
	// unparseable source) so one bad file does not abort the whole index run
	// (RESEARCH Assumptions Log A2, Pitfall 4). Additive extension of D-03's
	// File record.
	Errors        []string `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_internal_schema_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_internal_schema_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_internal_schema_graph_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *File) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *File) GetNodeCount() int64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *File) GetEdgeCount() int64 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

func (x *File) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Meta is the single versioned record (stored under the `meta/` key
// prefix, D-03) that stamps the on-disk schema version plus aggregate
// counts and index health. schema_version is bumped ONLY for a genuinely
// breaking layout change — additive field changes never require a bump
// (D-02a).
type Meta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion  uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	NodeCount      int64                  `protobuf:"varint,2,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	EdgeCount      int64                  `protobuf:"varint,3,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	LastSyncUnixMs int64                  `protobuf:"varint,4,opt,name=last_sync_unix_ms,json=lastSyncUnixMs,proto3" json:"last_sync_unix_ms,omitempty"`
	Healthy        bool                   `protobuf:"varint,5,opt,name=healthy,proto3" json:"healthy,omitempty"`
	HealthMessage  string                 `protobuf:"bytes,6,opt,name=health_message,json=healthMessage,proto3" json:"health_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_internal_schema_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_schema_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_internal_schema_graph_proto_rawDescGZIP(), []int{3}
}

func (x *Meta) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Meta) GetNodeCount() int64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *Meta) GetEdgeCount() int64 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

func (x *Meta) GetLastSyncUnixMs() int64 {
	if x != nil {
		return x.LastSyncUnixMs
	}
	return 0
}

func (x *Meta) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *Meta) GetHealthMessage() string {
	if x != nil {
		return x.HealthMessage
	}
	return ""
}

var File_internal_schema_graph_proto protoreflect.FileDescriptor

const file_internal_schema_graph_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/schema/graph.proto\x12\fcodegraph.v1\"\xb2\x03\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\x0equalified_name\x18\x04 \x01(\tR\rqualifiedName\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"start_line\x18\a \x01(\x05R\tstartLine\x12\x19\n" +
	"\bend_line\x18\b \x01(\x05R\aendLine\x12\x1b\n" +
	"\tstart_col\x18\t \x01(\x05R\bstartCol\x12\x17\n" +
	"\aend_col\x18\n" +
	" \x01(\x05R\x06endCol\x12\x1c\n" +
	"\tsignature\x18\v \x01(\tR\tsignature\x12\x1c\n" +
	"\tdocstring\x18\f \x01(\tR\tdocstring\x12\x1e\n" +
	"\n" +
	"visibility\x18\r \x01(\tR\n" +
	"visibility\x12\x1f\n" +
	"\vis_exported\x18\x0e \x01(\bR\n" +
	"isExported\x12\x1f\n" +
	"\vreturn_type\x18\x0f \x01(\tR\n" +
	"returnTypeJ\x04\b2\x10<\"\x91\x02\n" +
	"\x04Edge\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04line\x18\x04 \x01(\x05R\x04line\x12\x10\n" +
	"\x03col\x18\x05 \x01(\x05R\x03col\x12\x1e\n" +
	"\n" +
	"provenance\x18\x06 \x01(\tR\n" +
	"provenance\x12<\n" +
	"\bmetadata\x18\a \x03(\v2 .codegraph.v1.Edge.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b2\x10<\"\xaf\x01\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fcontent_hash\x18\x02 \x01(\tR\vcontentHash\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"node_count\x18\x04 \x01(\x03R\tnodeCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x05 \x01(\x03R\tedgeCount\x12\x16\n" +
	"\x06errors\x18\x06 \x03(\tR\x06errors\"\xd7\x01\n" +
	"\x04Meta\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x1d\n" +
	"\n" +
	"node_count\x18\x02 \x01(\x03R\tnodeCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x03 \x01(\x03R\tedgeCount\x12)\n" +
	"\x11last_sync_unix_ms\x18\x04 \x01(\x03R\x0elastSyncUnixMs\x12\x18\n" +
	"\ahealthy\x18\x05 \x01(\bR\ahealthy\x12%\n" +
	"\x0ehealth_message\x18\x06 \x01(\tR\rhealthMessageB1Z/github.com/seanb4t/codegraph-go/internal/schemab\x06proto3"

var (
	file_internal_schema_graph_proto_rawDescOnce sync.Once
	file_internal_schema_graph_proto_rawDescData []byte
)

func file_internal_schema_graph_proto_rawDescGZIP() []byte {
	file_internal_schema_graph_proto_rawDescOnce.Do(func() {
		file_internal_schema_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_schema_graph_proto_rawDesc), len(file_internal_schema_graph_proto_rawDesc)))
	})
	return file_internal_schema_graph_proto_rawDescData
}

var file_internal_schema_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_schema_graph_proto_goTypes = []any{
	(*Node)(nil), // 0: codegraph.v1.Node
	(*Edge)(nil), // 1: codegraph.v1.Edge
	(*File)(nil), // 2: codegraph.v1.File
	(*Meta)(nil), // 3: codegraph.v1.Meta
	nil,          // 4: codegraph.v1.Edge.MetadataEntry
}
var file_internal_schema_graph_proto_depIdxs = []int32{
	4, // 0: codegraph.v1.Edge.metadata:type_name -> codegraph.v1.Edge.MetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_schema_graph_proto_init() }
func file_internal_schema_graph_proto_init() {
	if File_internal_schema_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_schema_graph_proto_rawDesc), len(file_internal_schema_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_schema_graph_proto_goTypes,
		DependencyIndexes: file_internal_schema_graph_proto_depIdxs,
		MessageInfos:      file_internal_schema_graph_proto_msgTypes,
	}.Build()
	File_internal_schema_graph_proto = out.File
	file_internal_schema_graph_proto_goTypes = nil
	file_internal_schema_graph_proto_depIdxs = nil
}
