// Command clidoc is DOCS-05's generator: it builds the full codegraph
// Cobra tree via internal/cli.NewRootCmd(), completes it with the
// completion command family and the -v/--version flag — both are
// otherwise registered only inside Command.ExecuteC() at execute time, so
// a plain, unexecuted tree never sees either — walks every available command in
// Cobra's own alphabetical order, and calls doc.GenMarkdownCustom once per
// documented command into ONE shared buffer. It writes exactly one file,
// the -out path, and never anything else. It never emits one file per
// command (cobra/doc's own GenMarkdownTree layout, rejected — D-02), never
// filters commands by a rule of its own (IsAvailableCommand() and
// IsAdditionalHelpTopicCommand() — cobra's own predicates — decide what's
// documented), and never sorts (Cobra's Commands() and pflag's SortFlags
// already sort; adding another sort would be redundant, not corrective).
//
// Exit codes: 0 = wrote -out successfully, 1 = build or write error.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	internalcli "github.com/seanb4t/codegraph-go/internal/cli"
)

func main() {
	out := flag.String("out", "docs/CLI-REFERENCE.md", "output path for the generated CLI reference")
	flag.Parse()

	root := internalcli.NewRootCmd()
	root.InitDefaultCompletionCmd() // completion family is otherwise invisible outside ExecuteC()
	root.InitDefaultVersionFlag()   // -v/--version is otherwise invisible outside ExecuteC()
	root.DisableAutoGenTag = true   // suppresses the date-stamped footer; propagates to every descendant via GenMarkdownCustom's own VisitParents walk

	var buf bytes.Buffer
	buf.WriteString("<!-- Generated by tools/clidoc from the live codegraph Cobra tree — never hand-edited. Regenerate with `task docs:cli`; `task docs:cli:drift` fails the build if this file is stale. -->\n\n")
	buf.WriteString("# codegraph CLI reference\n\n")
	buf.WriteString("This file documents every non-hidden codegraph command and flag; it is generated from the same command tree the binary runs, so `codegraph <command> --help` prints the same text as the matching section below (hidden commands are intentionally omitted).\n\n")

	if err := walk(root, &buf); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	if err := os.WriteFile(*out, buf.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// documented reports whether cmd is one cobra/doc's own tree generator
// would descend into and render — the exact predicate GenMarkdownTreeCustom
// uses at the top of its loop (md_docs.go), copied here rather than called
// through GenMarkdownTree/GenMarkdownTreeCustom directly, since D-02
// requires single-file assembly, not cobra's one-file-per-command layout.
func documented(cmd *cobra.Command) bool {
	return cmd.IsAvailableCommand() && !cmd.IsAdditionalHelpTopicCommand()
}

// walk renders cmd (root is rendered too, matching what a real
// `codegraph --help` implies exists at the top of the tree) then recurses
// into every documented child, in Cobra's own pre-order/alphabetical
// traversal. It never descends into an undocumented command, so a hidden
// command's children are omitted along with it.
func walk(cmd *cobra.Command, buf *bytes.Buffer) error {
	if err := doc.GenMarkdownCustom(cmd, buf, linkHandler); err != nil {
		return fmt.Errorf("generate markdown for %s: %w", cmd.CommandPath(), err)
	}
	for _, sub := range cmd.Commands() {
		if !documented(sub) {
			continue
		}
		if err := walk(sub, buf); err != nil {
			return err
		}
	}
	return nil
}

// linkHandler rewrites cobra's default "command_name.md" SEE ALSO target
// into a same-file GitHub-flavored-markdown anchor: cobra already replaced
// spaces with "_" in the link, so trimming ".md" and swapping "_" for "-"
// reproduces GitHub's own auto-heading-anchor for the matching "## "
// section — every cmd.CommandPath() in this tree is already lowercase
// ASCII, so no case-folding is needed.
func linkHandler(link string) string {
	name := strings.TrimSuffix(link, ".md")
	return "#" + strings.ReplaceAll(name, "_", "-")
}
